/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Loqui;
using Noggog;
using Noggog.Notifying;
using HarmonizeGit.GUI.Internals;
using ReactiveUI;
using System.Xml;
using System.Xml.Linq;
using System.IO;
using Noggog.Xml;
using Loqui.Xml;
using Loqui.Internal;
using System.Diagnostics;
using System.Collections.Specialized;

namespace HarmonizeGit.GUI
{
    #region Class
    public partial class Repository :
        LoquiNotifyingObject,
        IRepositoryInternal,
        ILoquiObjectSetter<Repository>,
        IEquatable<Repository>,
        IEqualsMask
    {
        #region Ctor
        public Repository()
        {
            _hasBeenSetTracker = new BitArray(((ILoquiObject)this).Registration.FieldCount);
            CustomCtor();
        }
        partial void CustomCtor();
        #endregion

        #region Nickname
        private String _Nickname;
        public String Nickname
        {
            get => this._Nickname;
            set => this.RaiseAndSetIfReferenceChanged(ref this._Nickname, value, nameof(Nickname));
        }
        #endregion
        #region Path
        private String _Path;
        public String Path
        {
            get => this._Path;
            set => this.RaiseAndSetIfReferenceChanged(ref this._Path, value, nameof(Path));
        }
        #endregion

        IMask<bool> IEqualsMask.GetEqualsIMask(object rhs, EqualsMaskHelper.Include include) => this.GetEqualsMask((IRepositoryInternalGetter)rhs, include);
        #region To String

        public void ToString(
            FileGeneration fg,
            string name = null)
        {
            RepositoryMixIn.ToString(
                item: this,
                name: name);
        }

        #endregion

        IMask<bool> ILoquiObjectGetter.GetHasBeenSetIMask() => this.GetHasBeenSetMask();
        #region Equals and Hash
        public override bool Equals(object obj)
        {
            if (!(obj is IRepositoryInternalGetter rhs)) return false;
            return ((RepositoryCommon)((IRepositoryInternalGetter)this).CommonInstance()).Equals(this, rhs);
        }

        public bool Equals(Repository obj)
        {
            return ((RepositoryCommon)((IRepositoryInternalGetter)this).CommonInstance()).Equals(this, obj);
        }

        public override int GetHashCode() => ((RepositoryCommon)((IRepositoryInternalGetter)this).CommonInstance()).GetHashCode(this);

        #endregion

        #region Xml Translation
        protected object XmlWriteTranslator => RepositoryXmlWriteTranslation.Instance;
        object IXmlItem.XmlWriteTranslator => this.XmlWriteTranslator;
        #region Xml Create
        [DebuggerStepThrough]
        public static Repository CreateFromXml(
            XElement node,
            MissingCreate missing = MissingCreate.New,
            Repository_TranslationMask translationMask = null)
        {
            return CreateFromXml(
                missing: missing,
                node: node,
                errorMask: null,
                translationMask: translationMask?.GetCrystal());
        }

        [DebuggerStepThrough]
        public static Repository CreateFromXml(
            XElement node,
            out Repository_ErrorMask errorMask,
            bool doMasks = true,
            Repository_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            var ret = CreateFromXml(
                missing: missing,
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask.GetCrystal());
            errorMask = Repository_ErrorMask.Factory(errorMaskBuilder);
            return ret;
        }

        public static Repository CreateFromXml(
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            MissingCreate missing = MissingCreate.New)
        {
            switch (missing)
            {
                case MissingCreate.New:
                case MissingCreate.Null:
                    if (node == null) return missing == MissingCreate.New ? new Repository() : null;
                    break;
                default:
                    break;
            }
            var ret = new Repository();
            try
            {
                foreach (var elem in node.Elements())
                {
                    RepositoryXmlCreateTranslation.FillPublicElementXml(
                        item: ret,
                        node: elem,
                        name: elem.Name.LocalName,
                        errorMask: errorMask,
                        translationMask: translationMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
            return ret;
        }

        public static Repository CreateFromXml(
            string path,
            MissingCreate missing = MissingCreate.New,
            Repository_TranslationMask translationMask = null)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            return CreateFromXml(
                missing: missing,
                node: node,
                translationMask: translationMask);
        }

        public static Repository CreateFromXml(
            string path,
            out Repository_ErrorMask errorMask,
            Repository_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            return CreateFromXml(
                missing: missing,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static Repository CreateFromXml(
            string path,
            ErrorMaskBuilder errorMask,
            Repository_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            return CreateFromXml(
                missing: missing,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask?.GetCrystal());
        }

        public static Repository CreateFromXml(
            Stream stream,
            MissingCreate missing = MissingCreate.New,
            Repository_TranslationMask translationMask = null)
        {
            var node = XDocument.Load(stream).Root;
            return CreateFromXml(
                missing: missing,
                node: node,
                translationMask: translationMask);
        }

        public static Repository CreateFromXml(
            Stream stream,
            out Repository_ErrorMask errorMask,
            Repository_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            var node = XDocument.Load(stream).Root;
            return CreateFromXml(
                missing: missing,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static Repository CreateFromXml(
            Stream stream,
            ErrorMaskBuilder errorMask,
            Repository_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            var node = XDocument.Load(stream).Root;
            return CreateFromXml(
                missing: missing,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask?.GetCrystal());
        }

        #endregion

        #region Xml Copy In
        public void CopyInXml(
            XElement node,
            MissingCreate missing = MissingCreate.New)
        {
            CopyInXml_Internal(
                missing: missing,
                node: node,
                errorMask: null,
                translationMask: null);
        }

        public virtual void CopyInXml(
            XElement node,
            out Repository_ErrorMask errorMask,
            Repository_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New,
            bool doMasks = true)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            CopyInXml_Internal(
                missing: missing,
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = Repository_ErrorMask.Factory(errorMaskBuilder);
        }

        protected void CopyInXml_Internal(
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            MissingCreate missing = MissingCreate.New)
        {
            LoquiXmlTranslation<Repository>.Instance.CopyIn(
                missing: missing,
                node: node,
                item: this,
                skipProtected: true,
                errorMask: errorMask,
                translationMask: translationMask);
        }

        public void CopyInXml(
            string path,
            MissingCreate missing = MissingCreate.New)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            this.CopyInXml(
                missing: missing,
                node: node);
        }

        public void CopyInXml(
            string path,
            out Repository_ErrorMask errorMask,
            Repository_TranslationMask translationMask,
            MissingCreate missing = MissingCreate.New,
            bool doMasks = true)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            this.CopyInXml(
                missing: missing,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask,
                doMasks: doMasks);
        }

        public void CopyInXml(
            Stream stream,
            MissingCreate missing = MissingCreate.New)
        {
            var node = XDocument.Load(stream).Root;
            this.CopyInXml(
                missing: missing,
                node: node);
        }

        public void CopyInXml(
            Stream stream,
            out Repository_ErrorMask errorMask,
            Repository_TranslationMask translationMask,
            MissingCreate missing = MissingCreate.New,
            bool doMasks = true)
        {
            var node = XDocument.Load(stream).Root;
            this.CopyInXml(
                missing: missing,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask,
                doMasks: doMasks);
        }

        #endregion

        #endregion

        protected readonly BitArray _hasBeenSetTracker;
        protected bool GetHasBeenSet(int index)
        {
            switch ((Repository_FieldIndex)index)
            {
                case Repository_FieldIndex.Nickname:
                case Repository_FieldIndex.Path:
                    return true;
                default:
                    throw new ArgumentException($"Unknown field index: {index}");
            }
        }

        public Repository Copy(
            Repository_CopyMask copyMask = null,
            Repository def = null)
        {
            return Repository.Copy(
                this,
                copyMask: copyMask,
                def: def);
        }

        public static Repository Copy(
            Repository item,
            Repository_CopyMask copyMask = null,
            Repository def = null)
        {
            Repository ret;
            if (item.GetType().Equals(typeof(Repository)))
            {
                ret = new Repository();
            }
            else
            {
                ret = (Repository)System.Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public static Repository Copy_ToLoqui(
            Repository item,
            Repository_CopyMask copyMask = null,
            Repository def = null)
        {
            Repository ret;
            if (item.GetType().Equals(typeof(Repository)))
            {
                ret = new Repository() as Repository;
            }
            else
            {
                ret = (Repository)System.Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public void CopyFieldsFrom(Repository rhs)
        {
            this.CopyFieldsFrom(
                rhs: rhs,
                def: null,
                doMasks: false,
                errorMask: out var errMask,
                copyMask: null);
        }

        public void CopyFieldsFrom(
            Repository rhs,
            Repository_CopyMask copyMask,
            Repository def = null)
        {
            this.CopyFieldsFrom(
                rhs: rhs,
                def: def,
                doMasks: false,
                errorMask: out var errMask,
                copyMask: copyMask);
        }

        public void CopyFieldsFrom(
            Repository rhs,
            out Repository_ErrorMask errorMask,
            Repository_CopyMask copyMask = null,
            Repository def = null,
            bool doMasks = true)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            RepositorySetterCopyCommon.CopyFieldsFrom(
                item: this,
                rhs: rhs,
                def: def,
                errorMask: errorMaskBuilder,
                copyMask: copyMask);
            errorMask = Repository_ErrorMask.Factory(errorMaskBuilder);
        }

        public void CopyFieldsFrom(
            Repository rhs,
            ErrorMaskBuilder errorMask,
            Repository_CopyMask copyMask = null,
            Repository def = null)
        {
            RepositorySetterCopyCommon.CopyFieldsFrom(
                item: this,
                rhs: rhs,
                def: def,
                errorMask: errorMask,
                copyMask: copyMask);
        }

        protected void SetNthObject(ushort index, object obj)
        {
            Repository_FieldIndex enu = (Repository_FieldIndex)index;
            switch (enu)
            {
                case Repository_FieldIndex.Nickname:
                    this.Nickname = (String)obj;
                    break;
                case Repository_FieldIndex.Path:
                    this.Path = (String)obj;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void Clear()
        {
            RepositorySetterCommon.Instance.Clear(this);
        }

        public static Repository Create(IEnumerable<KeyValuePair<ushort, object>> fields)
        {
            var ret = new Repository();
            foreach (var pair in fields)
            {
                CopyInInternal_Repository(ret, pair);
            }
            return ret;
        }

        protected static void CopyInInternal_Repository(Repository obj, KeyValuePair<ushort, object> pair)
        {
            if (!EnumExt.TryParse(pair.Key, out Repository_FieldIndex enu))
            {
                throw new ArgumentException($"Unknown index: {pair.Key}");
            }
            switch (enu)
            {
                case Repository_FieldIndex.Nickname:
                    obj.Nickname = (String)pair.Value;
                    break;
                case Repository_FieldIndex.Path:
                    obj.Path = (String)pair.Value;
                    break;
                default:
                    throw new ArgumentException($"Unknown enum type: {enu}");
            }
        }
    }
    #endregion

    #region Interface
    public partial interface IRepository :
        IRepositoryInternalGetter,
        ILoquiObjectSetter<IRepositoryInternal>
    {
        new String Nickname { get; set; }

        new String Path { get; set; }

        void CopyFieldsFrom(
            Repository rhs,
            ErrorMaskBuilder errorMask = null,
            Repository_CopyMask copyMask = null,
            Repository def = null);
    }

    public partial interface IRepositoryInternal :
        IRepository,
        IRepositoryInternalGetter
    {
    }

    public partial interface IRepositoryGetter :
        ILoquiObject,
        ILoquiObject<IRepositoryInternalGetter>,
        IXmlItem
    {
        #region Nickname
        String Nickname { get; }

        #endregion
        #region Path
        String Path { get; }

        #endregion

    }

    public partial interface IRepositoryInternalGetter : IRepositoryGetter
    {
        object CommonInstance();
        object CommonSetterInstance();
        object CommonSetterCopyInstance();

    }

    #endregion

    #region Common MixIn
    public static class RepositoryMixIn
    {
        public static void Clear(this IRepositoryInternal item)
        {
            ((RepositorySetterCommon)((IRepositoryInternalGetter)item).CommonSetterInstance()).Clear(item: item);
        }

        public static Repository_Mask<bool> GetEqualsMask(
            this IRepositoryInternalGetter item,
            IRepositoryInternalGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            return ((RepositoryCommon)((IRepositoryInternalGetter)item).CommonInstance()).GetEqualsMask(
                item: item,
                rhs: rhs,
                include: include);
        }

        public static string ToString(
            this IRepositoryInternalGetter item,
            string name = null,
            Repository_Mask<bool> printMask = null)
        {
            return ((RepositoryCommon)((IRepositoryInternalGetter)item).CommonInstance()).ToString(
                item: item,
                name: name,
                printMask: printMask);
        }

        public static void ToString(
            this IRepositoryInternalGetter item,
            FileGeneration fg,
            string name = null,
            Repository_Mask<bool> printMask = null)
        {
            ((RepositoryCommon)((IRepositoryInternalGetter)item).CommonInstance()).ToString(
                item: item,
                fg: fg,
                name: name,
                printMask: printMask);
        }

        public static bool HasBeenSet(
            this IRepositoryInternalGetter item,
            Repository_Mask<bool?> checkMask)
        {
            return ((RepositoryCommon)((IRepositoryInternalGetter)item).CommonInstance()).HasBeenSet(
                item: item,
                checkMask: checkMask);
        }

        public static Repository_Mask<bool> GetHasBeenSetMask(this IRepositoryInternalGetter item)
        {
            var ret = new Repository_Mask<bool>();
            ((RepositoryCommon)((IRepositoryInternalGetter)item).CommonInstance()).FillHasBeenSetMask(
                item: item,
                mask: ret);
            return ret;
        }

        public static bool Equals(
            this IRepositoryInternalGetter item,
            IRepositoryInternalGetter rhs)
        {
            return ((RepositoryCommon)((IRepositoryInternalGetter)item).CommonInstance()).Equals(
                lhs: item,
                rhs: rhs);
        }

    }
    #endregion

}

namespace HarmonizeGit.GUI.Internals
{
    #region Field Index
    public enum Repository_FieldIndex
    {
        Nickname = 0,
        Path = 1,
    }
    #endregion

    #region Registration
    public class Repository_Registration : ILoquiRegistration
    {
        public static readonly Repository_Registration Instance = new Repository_Registration();

        public static ProtocolKey ProtocolKey => ProtocolDefinition_HarmonizeGit.ProtocolKey;

        public static readonly ObjectKey ObjectKey = new ObjectKey(
            protocolKey: ProtocolDefinition_HarmonizeGit.ProtocolKey,
            msgID: 2,
            version: 0);

        public const string GUID = "257a1e5e-e6be-4675-a3e4-a186db23e839";

        public const ushort AdditionalFieldCount = 2;

        public const ushort FieldCount = 2;

        public static readonly Type MaskType = typeof(Repository_Mask<>);

        public static readonly Type ErrorMaskType = typeof(Repository_ErrorMask);

        public static readonly Type ClassType = typeof(Repository);

        public static readonly Type GetterType = typeof(IRepositoryGetter);

        public static readonly Type InternalGetterType = typeof(IRepositoryInternalGetter);

        public static readonly Type SetterType = typeof(IRepository);

        public static readonly Type InternalSetterType = typeof(IRepositoryInternal);

        public const string FullName = "HarmonizeGit.GUI.Repository";

        public const string Name = "Repository";

        public const string Namespace = "HarmonizeGit.GUI";

        public const byte GenericCount = 0;

        public static readonly Type GenericRegistrationType = null;

        public static ushort? GetNameIndex(StringCaseAgnostic str)
        {
            switch (str.Upper)
            {
                case "NICKNAME":
                    return (ushort)Repository_FieldIndex.Nickname;
                case "PATH":
                    return (ushort)Repository_FieldIndex.Path;
                default:
                    return null;
            }
        }

        public static bool GetNthIsEnumerable(ushort index)
        {
            Repository_FieldIndex enu = (Repository_FieldIndex)index;
            switch (enu)
            {
                case Repository_FieldIndex.Nickname:
                case Repository_FieldIndex.Path:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsLoqui(ushort index)
        {
            Repository_FieldIndex enu = (Repository_FieldIndex)index;
            switch (enu)
            {
                case Repository_FieldIndex.Nickname:
                case Repository_FieldIndex.Path:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsSingleton(ushort index)
        {
            Repository_FieldIndex enu = (Repository_FieldIndex)index;
            switch (enu)
            {
                case Repository_FieldIndex.Nickname:
                case Repository_FieldIndex.Path:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static string GetNthName(ushort index)
        {
            Repository_FieldIndex enu = (Repository_FieldIndex)index;
            switch (enu)
            {
                case Repository_FieldIndex.Nickname:
                    return "Nickname";
                case Repository_FieldIndex.Path:
                    return "Path";
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsNthDerivative(ushort index)
        {
            Repository_FieldIndex enu = (Repository_FieldIndex)index;
            switch (enu)
            {
                case Repository_FieldIndex.Nickname:
                case Repository_FieldIndex.Path:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsProtected(ushort index)
        {
            Repository_FieldIndex enu = (Repository_FieldIndex)index;
            switch (enu)
            {
                case Repository_FieldIndex.Nickname:
                case Repository_FieldIndex.Path:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static Type GetNthType(ushort index)
        {
            Repository_FieldIndex enu = (Repository_FieldIndex)index;
            switch (enu)
            {
                case Repository_FieldIndex.Nickname:
                    return typeof(String);
                case Repository_FieldIndex.Path:
                    return typeof(String);
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static readonly Type XmlWriteTranslation = typeof(RepositoryXmlWriteTranslation);
        #region Interface
        ProtocolKey ILoquiRegistration.ProtocolKey => ProtocolKey;
        ObjectKey ILoquiRegistration.ObjectKey => ObjectKey;
        string ILoquiRegistration.GUID => GUID;
        ushort ILoquiRegistration.FieldCount => FieldCount;
        ushort ILoquiRegistration.AdditionalFieldCount => AdditionalFieldCount;
        Type ILoquiRegistration.MaskType => MaskType;
        Type ILoquiRegistration.ErrorMaskType => ErrorMaskType;
        Type ILoquiRegistration.ClassType => ClassType;
        Type ILoquiRegistration.SetterType => SetterType;
        Type ILoquiRegistration.InternalSetterType => InternalSetterType;
        Type ILoquiRegistration.GetterType => GetterType;
        Type ILoquiRegistration.InternalGetterType => InternalGetterType;
        string ILoquiRegistration.FullName => FullName;
        string ILoquiRegistration.Name => Name;
        string ILoquiRegistration.Namespace => Namespace;
        byte ILoquiRegistration.GenericCount => GenericCount;
        Type ILoquiRegistration.GenericRegistrationType => GenericRegistrationType;
        ushort? ILoquiRegistration.GetNameIndex(StringCaseAgnostic name) => GetNameIndex(name);
        bool ILoquiRegistration.GetNthIsEnumerable(ushort index) => GetNthIsEnumerable(index);
        bool ILoquiRegistration.GetNthIsLoqui(ushort index) => GetNthIsLoqui(index);
        bool ILoquiRegistration.GetNthIsSingleton(ushort index) => GetNthIsSingleton(index);
        string ILoquiRegistration.GetNthName(ushort index) => GetNthName(index);
        bool ILoquiRegistration.IsNthDerivative(ushort index) => IsNthDerivative(index);
        bool ILoquiRegistration.IsProtected(ushort index) => IsProtected(index);
        Type ILoquiRegistration.GetNthType(ushort index) => GetNthType(index);
        #endregion

    }
    #endregion

    #region Common
    public partial class RepositorySetterCommon
    {
        public static readonly RepositorySetterCommon Instance = new RepositorySetterCommon();

        partial void ClearPartial();
        
        public virtual void Clear(IRepositoryInternal item)
        {
            ClearPartial();
            item.Nickname = default(String);
            item.Path = default(String);
        }
        
        
    }
    public partial class RepositoryCommon
    {
        public static readonly RepositoryCommon Instance = new RepositoryCommon();

        public Repository_Mask<bool> GetEqualsMask(
            IRepositoryInternalGetter item,
            IRepositoryInternalGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            var ret = new Repository_Mask<bool>();
            ((RepositoryCommon)((IRepositoryInternalGetter)item).CommonInstance()).FillEqualsMask(
                item: item,
                rhs: rhs,
                ret: ret,
                include: include);
            return ret;
        }
        
        public void FillEqualsMask(
            IRepositoryInternalGetter item,
            IRepositoryInternalGetter rhs,
            Repository_Mask<bool> ret,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            if (rhs == null) return;
            ret.Nickname = string.Equals(item.Nickname, rhs.Nickname);
            ret.Path = string.Equals(item.Path, rhs.Path);
        }
        
        public string ToString(
            IRepositoryInternalGetter item,
            string name = null,
            Repository_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            ToString(
                item: item,
                fg: fg,
                name: name,
                printMask: printMask);
            return fg.ToString();
        }
        
        public void ToString(
            IRepositoryInternalGetter item,
            FileGeneration fg,
            string name = null,
            Repository_Mask<bool> printMask = null)
        {
            if (name == null)
            {
                fg.AppendLine($"Repository =>");
            }
            else
            {
                fg.AppendLine($"{name} (Repository) =>");
            }
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                ToStringFields(
                    item: item,
                    fg: fg,
                    printMask: printMask);
            }
            fg.AppendLine("]");
        }
        
        protected static void ToStringFields(
            IRepositoryInternalGetter item,
            FileGeneration fg,
            Repository_Mask<bool> printMask = null)
        {
            if (printMask?.Nickname ?? true)
            {
                fg.AppendLine($"Nickname => {item.Nickname}");
            }
            if (printMask?.Path ?? true)
            {
                fg.AppendLine($"Path => {item.Path}");
            }
        }
        
        public bool HasBeenSet(
            IRepositoryInternalGetter item,
            Repository_Mask<bool?> checkMask)
        {
            return true;
        }
        
        public void FillHasBeenSetMask(
            IRepositoryInternalGetter item,
            Repository_Mask<bool> mask)
        {
            mask.Nickname = true;
            mask.Path = true;
        }
        
        #region Equals and Hash
        public virtual bool Equals(
            IRepositoryInternalGetter lhs,
            IRepositoryInternalGetter rhs)
        {
            if (lhs == null && rhs == null) return false;
            if (lhs == null || rhs == null) return false;
            if (!string.Equals(lhs.Nickname, rhs.Nickname)) return false;
            if (!string.Equals(lhs.Path, rhs.Path)) return false;
            return true;
        }
        
        public virtual int GetHashCode(IRepositoryInternalGetter item)
        {
            int ret = 0;
            ret = HashHelper.GetHashCode(item.Nickname).CombineHashCode(ret);
            ret = HashHelper.GetHashCode(item.Path).CombineHashCode(ret);
            return ret;
        }
        
        #endregion
        
        
        
    }
    public partial class RepositorySetterCopyCommon
    {
        public static readonly RepositorySetterCopyCommon Instance = new RepositorySetterCopyCommon();

        #region Copy Fields From
        public static void CopyFieldsFrom(
            Repository item,
            Repository rhs,
            Repository def,
            ErrorMaskBuilder errorMask,
            Repository_CopyMask copyMask)
        {
            if (copyMask?.Nickname ?? true)
            {
                errorMask?.PushIndex((int)Repository_FieldIndex.Nickname);
                try
                {
                    item.Nickname = rhs.Nickname;
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
            if (copyMask?.Path ?? true)
            {
                errorMask?.PushIndex((int)Repository_FieldIndex.Path);
                try
                {
                    item.Path = rhs.Path;
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
        }
        
        #endregion
        
        
    }
    #endregion

    #region Modules
    #region Xml Translation
    public partial class RepositoryXmlWriteTranslation : IXmlWriteTranslator
    {
        public readonly static RepositoryXmlWriteTranslation Instance = new RepositoryXmlWriteTranslation();

        public static void WriteToNodeXml(
            IRepositoryInternalGetter item,
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            if ((translationMask?.GetShouldTranslate((int)Repository_FieldIndex.Nickname) ?? true))
            {
                StringXmlTranslation.Instance.Write(
                    node: node,
                    name: nameof(item.Nickname),
                    item: item.Nickname,
                    fieldIndex: (int)Repository_FieldIndex.Nickname,
                    errorMask: errorMask);
            }
            if ((translationMask?.GetShouldTranslate((int)Repository_FieldIndex.Path) ?? true))
            {
                StringXmlTranslation.Instance.Write(
                    node: node,
                    name: nameof(item.Path),
                    item: item.Path,
                    fieldIndex: (int)Repository_FieldIndex.Path,
                    errorMask: errorMask);
            }
        }

        public void Write(
            XElement node,
            IRepositoryInternalGetter item,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            var elem = new XElement(name ?? "HarmonizeGit.GUI.Repository");
            node.Add(elem);
            if (name != null)
            {
                elem.SetAttributeValue("type", "HarmonizeGit.GUI.Repository");
            }
            WriteToNodeXml(
                item: item,
                node: elem,
                errorMask: errorMask,
                translationMask: translationMask);
        }

        public void Write(
            XElement node,
            object item,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            Write(
                item: (IRepositoryInternalGetter)item,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
        }

        public void Write(
            XElement node,
            IRepositoryInternalGetter item,
            ErrorMaskBuilder errorMask,
            int fieldIndex,
            TranslationCrystal translationMask,
            string name = null)
        {
            try
            {
                errorMask?.PushIndex(fieldIndex);
                Write(
                    item: (IRepositoryInternalGetter)item,
                    name: name,
                    node: node,
                    errorMask: errorMask,
                    translationMask: translationMask);
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
            finally
            {
                errorMask?.PopIndex();
            }
        }

    }

    public partial class RepositoryXmlCreateTranslation
    {
        public readonly static RepositoryXmlCreateTranslation Instance = new RepositoryXmlCreateTranslation();

        public static void FillPublicXml(
            IRepositoryInternal item,
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            try
            {
                foreach (var elem in node.Elements())
                {
                    RepositoryXmlCreateTranslation.FillPublicElementXml(
                        item: item,
                        node: elem,
                        name: elem.Name.LocalName,
                        errorMask: errorMask,
                        translationMask: translationMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
        }

        public static void FillPublicElementXml(
            IRepositoryInternal item,
            XElement node,
            string name,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            switch (name)
            {
                case "Nickname":
                    if ((translationMask?.GetShouldTranslate((int)Repository_FieldIndex.Nickname) ?? true))
                    {
                        try
                        {
                            errorMask?.PushIndex((int)Repository_FieldIndex.Nickname);
                            if (StringXmlTranslation.Instance.Parse(
                                node: node,
                                item: out String NicknameParse,
                                errorMask: errorMask))
                            {
                                item.Nickname = NicknameParse;
                            }
                            else
                            {
                                item.Nickname = default(String);
                            }
                        }
                        catch (Exception ex)
                        when (errorMask != null)
                        {
                            errorMask.ReportException(ex);
                        }
                        finally
                        {
                            errorMask?.PopIndex();
                        }
                    }
                    break;
                case "Path":
                    if ((translationMask?.GetShouldTranslate((int)Repository_FieldIndex.Path) ?? true))
                    {
                        try
                        {
                            errorMask?.PushIndex((int)Repository_FieldIndex.Path);
                            if (StringXmlTranslation.Instance.Parse(
                                node: node,
                                item: out String PathParse,
                                errorMask: errorMask))
                            {
                                item.Path = PathParse;
                            }
                            else
                            {
                                item.Path = default(String);
                            }
                        }
                        catch (Exception ex)
                        when (errorMask != null)
                        {
                            errorMask.ReportException(ex);
                        }
                        finally
                        {
                            errorMask?.PopIndex();
                        }
                    }
                    break;
                default:
                    break;
            }
        }

    }

    #region Xml Write Mixins
    public static class RepositoryXmlTranslationMixIn
    {
        public static void WriteToXml(
            this IRepositoryInternalGetter item,
            XElement node,
            out Repository_ErrorMask errorMask,
            bool doMasks = true,
            Repository_TranslationMask translationMask = null,
            string name = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            ((RepositoryXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = Repository_ErrorMask.Factory(errorMaskBuilder);
        }

        public static void WriteToXml(
            this IRepositoryInternalGetter item,
            string path,
            out Repository_ErrorMask errorMask,
            Repository_TranslationMask translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            var node = new XElement("topnode");
            WriteToXml(
                item: item,
                name: name,
                node: node,
                errorMask: out errorMask,
                doMasks: doMasks,
                translationMask: translationMask);
            node.Elements().First().SaveIfChanged(path);
        }

        public static void WriteToXml(
            this IRepositoryInternalGetter item,
            string path,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            var node = new XElement("topnode");
            WriteToXml(
                item: item,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
            node.Elements().First().SaveIfChanged(path);
        }

        public static void WriteToXml(
            this IRepositoryInternalGetter item,
            Stream stream,
            out Repository_ErrorMask errorMask,
            Repository_TranslationMask translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            var node = new XElement("topnode");
            WriteToXml(
                item: item,
                name: name,
                node: node,
                errorMask: out errorMask,
                doMasks: doMasks,
                translationMask: translationMask);
            node.Elements().First().Save(stream);
        }

        public static void WriteToXml(
            this IRepositoryInternalGetter item,
            Stream stream,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            var node = new XElement("topnode");
            WriteToXml(
                item: item,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
            node.Elements().First().Save(stream);
        }

        public static void WriteToXml(
            this IRepositoryInternalGetter item,
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask = null,
            string name = null)
        {
            ((RepositoryXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
        }

        public static void WriteToXml(
            this IRepositoryInternalGetter item,
            XElement node,
            string name = null,
            Repository_TranslationMask translationMask = null)
        {
            ((RepositoryXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: null,
                translationMask: translationMask.GetCrystal());
        }

        public static void WriteToXml(
            this IRepositoryInternalGetter item,
            string path,
            string name = null)
        {
            var node = new XElement("topnode");
            ((RepositoryXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: null,
                translationMask: null);
            node.Elements().First().SaveIfChanged(path);
        }

        public static void WriteToXml(
            this IRepositoryInternalGetter item,
            Stream stream,
            string name = null)
        {
            var node = new XElement("topnode");
            ((RepositoryXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: null,
                translationMask: null);
            node.Elements().First().Save(stream);
        }

    }
    #endregion

    #endregion

    #region Mask
    public class Repository_Mask<T> : IMask<T>, IEquatable<Repository_Mask<T>>
    {
        #region Ctors
        public Repository_Mask()
        {
        }

        public Repository_Mask(T initialValue)
        {
            this.Nickname = initialValue;
            this.Path = initialValue;
        }
        #endregion

        #region Members
        public T Nickname;
        public T Path;
        #endregion

        #region Equals
        public override bool Equals(object obj)
        {
            if (!(obj is Repository_Mask<T> rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(Repository_Mask<T> rhs)
        {
            if (rhs == null) return false;
            if (!object.Equals(this.Nickname, rhs.Nickname)) return false;
            if (!object.Equals(this.Path, rhs.Path)) return false;
            return true;
        }
        public override int GetHashCode()
        {
            int ret = 0;
            ret = ret.CombineHashCode(this.Nickname?.GetHashCode());
            ret = ret.CombineHashCode(this.Path?.GetHashCode());
            return ret;
        }

        #endregion

        #region All Equal
        public bool AllEqual(Func<T, bool> eval)
        {
            if (!eval(this.Nickname)) return false;
            if (!eval(this.Path)) return false;
            return true;
        }
        #endregion

        #region Translate
        public Repository_Mask<R> Translate<R>(Func<T, R> eval)
        {
            var ret = new Repository_Mask<R>();
            this.Translate_InternalFill(ret, eval);
            return ret;
        }

        protected void Translate_InternalFill<R>(Repository_Mask<R> obj, Func<T, R> eval)
        {
            obj.Nickname = eval(this.Nickname);
            obj.Path = eval(this.Path);
        }
        #endregion

        #region Clear Enumerables
        public void ClearEnumerables()
        {
        }
        #endregion

        #region To String
        public override string ToString()
        {
            return ToString(printMask: null);
        }

        public string ToString(Repository_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            ToString(fg, printMask);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg, Repository_Mask<bool> printMask = null)
        {
            fg.AppendLine($"{nameof(Repository_Mask<T>)} =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.Nickname ?? true)
                {
                    fg.AppendLine($"Nickname => {Nickname}");
                }
                if (printMask?.Path ?? true)
                {
                    fg.AppendLine($"Path => {Path}");
                }
            }
            fg.AppendLine("]");
        }
        #endregion

    }

    public class Repository_ErrorMask : IErrorMask, IErrorMask<Repository_ErrorMask>
    {
        #region Members
        public Exception Overall { get; set; }
        private List<string> _warnings;
        public List<string> Warnings
        {
            get
            {
                if (_warnings == null)
                {
                    _warnings = new List<string>();
                }
                return _warnings;
            }
        }
        public Exception Nickname;
        public Exception Path;
        #endregion

        #region IErrorMask
        public object GetNthMask(int index)
        {
            Repository_FieldIndex enu = (Repository_FieldIndex)index;
            switch (enu)
            {
                case Repository_FieldIndex.Nickname:
                    return Nickname;
                case Repository_FieldIndex.Path:
                    return Path;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthException(int index, Exception ex)
        {
            Repository_FieldIndex enu = (Repository_FieldIndex)index;
            switch (enu)
            {
                case Repository_FieldIndex.Nickname:
                    this.Nickname = ex;
                    break;
                case Repository_FieldIndex.Path:
                    this.Path = ex;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthMask(int index, object obj)
        {
            Repository_FieldIndex enu = (Repository_FieldIndex)index;
            switch (enu)
            {
                case Repository_FieldIndex.Nickname:
                    this.Nickname = (Exception)obj;
                    break;
                case Repository_FieldIndex.Path:
                    this.Path = (Exception)obj;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public bool IsInError()
        {
            if (Overall != null) return true;
            if (Nickname != null) return true;
            if (Path != null) return true;
            return false;
        }
        #endregion

        #region To String
        public override string ToString()
        {
            var fg = new FileGeneration();
            ToString(fg);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg)
        {
            fg.AppendLine("Repository_ErrorMask =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (this.Overall != null)
                {
                    fg.AppendLine("Overall =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        fg.AppendLine($"{this.Overall}");
                    }
                    fg.AppendLine("]");
                }
                ToString_FillInternal(fg);
            }
            fg.AppendLine("]");
        }
        protected void ToString_FillInternal(FileGeneration fg)
        {
            fg.AppendLine($"Nickname => {Nickname}");
            fg.AppendLine($"Path => {Path}");
        }
        #endregion

        #region Combine
        public Repository_ErrorMask Combine(Repository_ErrorMask rhs)
        {
            var ret = new Repository_ErrorMask();
            ret.Nickname = this.Nickname.Combine(rhs.Nickname);
            ret.Path = this.Path.Combine(rhs.Path);
            return ret;
        }
        public static Repository_ErrorMask Combine(Repository_ErrorMask lhs, Repository_ErrorMask rhs)
        {
            if (lhs != null && rhs != null) return lhs.Combine(rhs);
            return lhs ?? rhs;
        }
        #endregion

        #region Factory
        public static Repository_ErrorMask Factory(ErrorMaskBuilder errorMask)
        {
            if (errorMask?.Empty ?? true) return null;
            return new Repository_ErrorMask();
        }
        #endregion

    }
    public class Repository_CopyMask
    {
        public Repository_CopyMask()
        {
        }

        public Repository_CopyMask(bool defaultOn, CopyOption deepCopyOption = CopyOption.Reference)
        {
            this.Nickname = defaultOn;
            this.Path = defaultOn;
        }

        #region Members
        public bool Nickname;
        public bool Path;
        #endregion

    }

    public class Repository_TranslationMask : ITranslationMask
    {
        #region Members
        private TranslationCrystal _crystal;
        public bool Nickname;
        public bool Path;
        #endregion

        #region Ctors
        public Repository_TranslationMask()
        {
        }

        public Repository_TranslationMask(bool defaultOn)
        {
            this.Nickname = defaultOn;
            this.Path = defaultOn;
        }

        #endregion

        public TranslationCrystal GetCrystal()
        {
            if (_crystal != null) return _crystal;
            List<(bool On, TranslationCrystal SubCrystal)> ret = new List<(bool On, TranslationCrystal SubCrystal)>();
            GetCrystal(ret);
            _crystal = new TranslationCrystal()
            {
                Crystal = ret.ToArray()
            };
            return _crystal;
        }

        protected void GetCrystal(List<(bool On, TranslationCrystal SubCrystal)> ret)
        {
            ret.Add((Nickname, null));
            ret.Add((Path, null));
        }
    }
    #endregion

    #endregion

}

namespace HarmonizeGit.GUI
{
    public partial class Repository
    {
        #region Common Routing
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => Repository_Registration.Instance;
        public static Repository_Registration Registration => Repository_Registration.Instance;
        protected object CommonInstance()
        {
            return RepositoryCommon.Instance;
        }
        protected object CommonSetterInstance()
        {
            return RepositorySetterCommon.Instance;
        }
        protected object CommonSetterCopyInstance()
        {
            return RepositorySetterCopyCommon.Instance;
        }
        object IRepositoryInternalGetter.CommonInstance()
        {
            return this.CommonInstance();
        }
        object IRepositoryInternalGetter.CommonSetterInstance()
        {
            return this.CommonSetterInstance();
        }
        object IRepositoryInternalGetter.CommonSetterCopyInstance()
        {
            return this.CommonSetterCopyInstance();
        }

        #endregion

    }
}
