/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Loqui;
using Noggog;
using Noggog.Notifying;
using HarmonizeGitCloner.Internals;
using System.Xml;
using System.Xml.Linq;
using System.IO;
using Noggog.Xml;
using Loqui.Xml;

namespace HarmonizeGitCloner
{
    #region Class
    public partial class Clone : IClone, ILoquiObjectSetter, IEquatable<Clone>
    {
        ILoquiRegistration ILoquiObject.Registration => Clone_Registration.Instance;
        public static Clone_Registration Registration => Clone_Registration.Instance;

        #region Ctor
        public Clone()
        {
            CustomCtor();
        }
        partial void CustomCtor();
        #endregion

        #region Nickname
        public String Nickname { get; set; }
        #endregion
        #region ClonePath
        public String ClonePath { get; set; }
        #endregion

        #region Loqui Getter Interface

        protected object GetNthObject(ushort index) => CloneCommon.GetNthObject(index, this);
        object ILoquiObjectGetter.GetNthObject(ushort index) => this.GetNthObject(index);

        protected bool GetNthObjectHasBeenSet(ushort index) => CloneCommon.GetNthObjectHasBeenSet(index, this);
        bool ILoquiObjectGetter.GetNthObjectHasBeenSet(ushort index) => this.GetNthObjectHasBeenSet(index);

        protected void UnsetNthObject(ushort index, NotifyingUnsetParameters? cmds) => CloneCommon.UnsetNthObject(index, this, cmds);
        void ILoquiObjectSetter.UnsetNthObject(ushort index, NotifyingUnsetParameters? cmds) => this.UnsetNthObject(index, cmds);

        #endregion

        #region Loqui Interface
        protected void SetNthObjectHasBeenSet(ushort index, bool on)
        {
            CloneCommon.SetNthObjectHasBeenSet(index, on, this);
        }
        void ILoquiObjectSetter.SetNthObjectHasBeenSet(ushort index, bool on) => this.SetNthObjectHasBeenSet(index, on);

        #endregion

        #region To String
        public override string ToString()
        {
            return CloneCommon.ToString(this, printMask: null);
        }

        public string ToString(
            string name = null,
            Clone_Mask<bool> printMask = null)
        {
            return CloneCommon.ToString(this, name: name, printMask: printMask);
        }

        public void ToString(
            FileGeneration fg,
            string name = null)
        {
            CloneCommon.ToString(this, fg, name: name, printMask: null);
        }

        #endregion

        public Clone_Mask<bool> GetHasBeenSetMask()
        {
            return CloneCommon.GetHasBeenSetMask(this);
        }
        #region Equals and Hash
        public override bool Equals(object obj)
        {
            if (!(obj is Clone rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(Clone rhs)
        {
            if (rhs == null) return false;
            if (!object.Equals(Nickname, rhs.Nickname)) return false;
            if (!object.Equals(ClonePath, rhs.ClonePath)) return false;
            return true;
        }

        public override int GetHashCode()
        {
            int ret = 0;
            ret = HashHelper.GetHashCode(Nickname).CombineHashCode(ret);
            ret = HashHelper.GetHashCode(ClonePath).CombineHashCode(ret);
            return ret;
        }

        #endregion


        #region XML Translation
        #region XML Create
        public static Clone Create_XML(XElement root)
        {
            return Create_XML(
                root: root,
                doMasks: false,
                errorMask: out var errorMask);
        }

        public static Clone Create_XML(
            XElement root,
            out Clone_ErrorMask errorMask)
        {
            return Create_XML(
                root: root,
                doMasks: true,
                errorMask: out errorMask);
        }

        public static Clone Create_XML(
            XElement root,
            bool doMasks,
            out Clone_ErrorMask errorMask)
        {
            Clone_ErrorMask errMaskRet = null;
            var ret = Create_XML_Internal(
                root: root,
                doMasks: doMasks,
                errorMask: doMasks ? () => errMaskRet ?? (errMaskRet = new Clone_ErrorMask()) : default(Func<Clone_ErrorMask>));
            errorMask = errMaskRet;
            return ret;
        }

        public static Clone Create_XML(string path)
        {
            var root = XDocument.Load(path).Root;
            return Create_XML(root: root);
        }

        public static Clone Create_XML(
            string path,
            out Clone_ErrorMask errorMask)
        {
            var root = XDocument.Load(path).Root;
            return Create_XML(
                root: root,
                errorMask: out errorMask);
        }

        public static Clone Create_XML(Stream stream)
        {
            var root = XDocument.Load(stream).Root;
            return Create_XML(root: root);
        }

        public static Clone Create_XML(
            Stream stream,
            out Clone_ErrorMask errorMask)
        {
            var root = XDocument.Load(stream).Root;
            return Create_XML(
                root: root,
                errorMask: out errorMask);
        }

        #endregion

        #region XML Copy In
        public void CopyIn_XML(
            XElement root,
            NotifyingFireParameters? cmds = null)
        {
            LoquiXmlTranslation<Clone, Clone_ErrorMask>.Instance.CopyIn(
                root: root,
                item: this,
                skipProtected: true,
                doMasks: false,
                mask: out Clone_ErrorMask errorMask,
                cmds: cmds);
        }

        public virtual void CopyIn_XML(
            XElement root,
            out Clone_ErrorMask errorMask,
            NotifyingFireParameters? cmds = null)
        {
            LoquiXmlTranslation<Clone, Clone_ErrorMask>.Instance.CopyIn(
                root: root,
                item: this,
                skipProtected: true,
                doMasks: true,
                mask: out errorMask,
                cmds: cmds);
        }

        public void CopyIn_XML(
            string path,
            NotifyingFireParameters? cmds = null)
        {
            var root = XDocument.Load(path).Root;
            this.CopyIn_XML(
                root: root,
                cmds: cmds);
        }

        public void CopyIn_XML(
            string path,
            out Clone_ErrorMask errorMask,
            NotifyingFireParameters? cmds = null)
        {
            var root = XDocument.Load(path).Root;
            this.CopyIn_XML(
                root: root,
                errorMask: out errorMask,
                cmds: cmds);
        }

        public void CopyIn_XML(
            Stream stream,
            NotifyingFireParameters? cmds = null)
        {
            var root = XDocument.Load(stream).Root;
            this.CopyIn_XML(
                root: root,
                cmds: cmds);
        }

        public void CopyIn_XML(
            Stream stream,
            out Clone_ErrorMask errorMask,
            NotifyingFireParameters? cmds = null)
        {
            var root = XDocument.Load(stream).Root;
            this.CopyIn_XML(
                root: root,
                errorMask: out errorMask,
                cmds: cmds);
        }

        #endregion

        #region XML Write
        public virtual void Write_XML(
            XmlWriter writer,
            out Clone_ErrorMask errorMask,
            string name = null)
        {
            CloneCommon.Write_XML(
                writer: writer,
                name: name,
                item: this,
                doMasks: true,
                errorMask: out errorMask);
        }

        public virtual void Write_XML(
            string path,
            out Clone_ErrorMask errorMask,
            string name = null)
        {
            using (var writer = new XmlTextWriter(path, Encoding.ASCII))
            {
                writer.Formatting = Formatting.Indented;
                writer.Indentation = 3;
                Write_XML(
                    writer: writer,
                    name: name,
                    errorMask: out errorMask);
            }
        }

        public virtual void Write_XML(
            Stream stream,
            out Clone_ErrorMask errorMask,
            string name = null)
        {
            using (var writer = new XmlTextWriter(stream, Encoding.ASCII))
            {
                writer.Formatting = Formatting.Indented;
                writer.Indentation = 3;
                Write_XML(
                    writer: writer,
                    name: name,
                    errorMask: out errorMask);
            }
        }

        public void Write_XML(
            XmlWriter writer,
            string name = null)
        {
            CloneCommon.Write_XML(
                writer: writer,
                name: name,
                item: this,
                doMasks: false,
                errorMask: out Clone_ErrorMask errorMask);
        }

        public void Write_XML(
            string path,
            string name = null)
        {
            using (var writer = new XmlTextWriter(path, Encoding.ASCII))
            {
                writer.Formatting = Formatting.Indented;
                writer.Indentation = 3;
                Write_XML(
                    writer: writer,
                    name: name);
            }
        }

        public void Write_XML(
            Stream stream,
            string name = null)
        {
            using (var writer = new XmlTextWriter(stream, Encoding.ASCII))
            {
                writer.Formatting = Formatting.Indented;
                writer.Indentation = 3;
                Write_XML(
                    writer: writer,
                    name: name);
            }
        }

        #endregion

        private static Clone Create_XML_Internal(
            XElement root,
            bool doMasks,
            Func<Clone_ErrorMask> errorMask)
        {
            var ret = new Clone();
            try
            {
                foreach (var elem in root.Elements())
                {
                    Fill_XML_Internal(
                        item: ret,
                        root: elem,
                        name: elem.Name.LocalName,
                        doMasks: doMasks,
                        errorMask: errorMask);
                }
            }
            catch (Exception ex)
            when (doMasks)
            {
                errorMask().Overall = ex;
            }
            return ret;
        }

        protected static void Fill_XML_Internal(
            Clone item,
            XElement root,
            string name,
            bool doMasks,
            Func<Clone_ErrorMask> errorMask)
        {
            switch (name)
            {
                case "Nickname":
                    {
                        Exception subMask;
                        var tryGet = StringXmlTranslation.Instance.Parse(
                            root,
                            doMasks: doMasks,
                            errorMask: out subMask);
                        if (tryGet.Succeeded)
                        {
                            item.Nickname = tryGet.Value;
                        }
                        if (doMasks && subMask != null)
                        {
                            errorMask().Nickname = subMask;
                        }
                    }
                    break;
                case "ClonePath":
                    {
                        Exception subMask;
                        var tryGet = StringXmlTranslation.Instance.Parse(
                            root,
                            doMasks: doMasks,
                            errorMask: out subMask);
                        if (tryGet.Succeeded)
                        {
                            item.ClonePath = tryGet.Value;
                        }
                        if (doMasks && subMask != null)
                        {
                            errorMask().ClonePath = subMask;
                        }
                    }
                    break;
                default:
                    break;
            }
        }

        #endregion

        public Clone Copy(
            Clone_CopyMask copyMask = null,
            ICloneGetter def = null)
        {
            return Clone.Copy(
                this,
                copyMask: copyMask,
                def: def);
        }

        public static Clone Copy(
            IClone item,
            Clone_CopyMask copyMask = null,
            ICloneGetter def = null)
        {
            Clone ret;
            if (item.GetType().Equals(typeof(Clone)))
            {
                ret = new Clone();
            }
            else
            {
                ret = (Clone)Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public static CopyType CopyGeneric<CopyType>(
            CopyType item,
            Clone_CopyMask copyMask = null,
            ICloneGetter def = null)
            where CopyType : class, IClone
        {
            CopyType ret;
            if (item.GetType().Equals(typeof(Clone)))
            {
                ret = new Clone() as CopyType;
            }
            else
            {
                ret = (CopyType)Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                doErrorMask: false,
                errorMask: null,
                cmds: null,
                def: def);
            return ret;
        }

        public static Clone Copy_ToLoqui(
            ICloneGetter item,
            Clone_CopyMask copyMask = null,
            ICloneGetter def = null)
        {
            var ret = new Clone();
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        void ILoquiObjectSetter.SetNthObject(ushort index, object obj, NotifyingFireParameters? cmds) => this.SetNthObject(index, obj, cmds);
        protected void SetNthObject(ushort index, object obj, NotifyingFireParameters? cmds = null)
        {
            Clone_FieldIndex enu = (Clone_FieldIndex)index;
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                    this.Nickname = (String)obj;
                    break;
                case Clone_FieldIndex.ClonePath:
                    this.ClonePath = (String)obj;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        partial void ClearPartial(NotifyingUnsetParameters? cmds);

        protected void CallClearPartial_Internal(NotifyingUnsetParameters? cmds)
        {
            ClearPartial(cmds);
        }

        public void Clear(NotifyingUnsetParameters? cmds = null)
        {
            CallClearPartial_Internal(cmds);
            CloneCommon.Clear(this, cmds);
        }


        public static Clone Create(IEnumerable<KeyValuePair<ushort, object>> fields)
        {
            var ret = new Clone();
            foreach (var pair in fields)
            {
                CopyInInternal_Clone(ret, pair);
            }
            return ret;
        }

        protected static void CopyInInternal_Clone(Clone obj, KeyValuePair<ushort, object> pair)
        {
            if (!EnumExt.TryParse(pair.Key, out Clone_FieldIndex enu))
            {
                throw new ArgumentException($"Unknown index: {pair.Key}");
            }
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                    obj.Nickname = (String)pair.Value;
                    break;
                case Clone_FieldIndex.ClonePath:
                    obj.ClonePath = (String)pair.Value;
                    break;
                default:
                    throw new ArgumentException($"Unknown enum type: {enu}");
            }
        }
        public static void CopyIn(IEnumerable<KeyValuePair<ushort, object>> fields, Clone obj)
        {
            ILoquiObjectExt.CopyFieldsIn(obj, fields, def: null, skipProtected: false, cmds: null);
        }

    }
    #endregion

    #region Interface
    public interface IClone : ICloneGetter, ILoquiClass<IClone, ICloneGetter>, ILoquiClass<Clone, ICloneGetter>
    {
        new String Nickname { get; set; }

        new String ClonePath { get; set; }

    }

    public interface ICloneGetter : ILoquiObject
    {
        #region Nickname
        String Nickname { get; }

        #endregion
        #region ClonePath
        String ClonePath { get; }

        #endregion

    }

    #endregion

}

namespace HarmonizeGitCloner.Internals
{
    #region Field Index
    public enum Clone_FieldIndex
    {
        Nickname = 0,
        ClonePath = 1,
    }
    #endregion

    #region Registration
    public class Clone_Registration : ILoquiRegistration
    {
        public static readonly Clone_Registration Instance = new Clone_Registration();

        public static ProtocolKey ProtocolKey => ProtocolDefinition_HarmonizeGitCloner.ProtocolKey;

        public static readonly ObjectKey ObjectKey = new ObjectKey(
            protocolKey: ProtocolDefinition_HarmonizeGitCloner.ProtocolKey,
            msgID: 2,
            version: 0);

        public const string GUID = "0bfc02a5-d0a6-4133-a58a-de62dd81525c";

        public const ushort FieldCount = 2;

        public static readonly Type MaskType = typeof(Clone_Mask<>);

        public static readonly Type ErrorMaskType = typeof(Clone_ErrorMask);

        public static readonly Type ClassType = typeof(Clone);

        public static readonly Type GetterType = typeof(ICloneGetter);

        public static readonly Type SetterType = typeof(IClone);

        public static readonly Type CommonType = typeof(CloneCommon);

        public const string FullName = "HarmonizeGitCloner.Clone";

        public const string Name = "Clone";

        public const string Namespace = "HarmonizeGitCloner";

        public const byte GenericCount = 0;

        public static readonly Type GenericRegistrationType = null;

        public static ushort? GetNameIndex(StringCaseAgnostic str)
        {
            switch (str.Upper)
            {
                case "NICKNAME":
                    return (ushort)Clone_FieldIndex.Nickname;
                case "CLONEPATH":
                    return (ushort)Clone_FieldIndex.ClonePath;
                default:
                    return null;
            }
        }

        public static bool GetNthIsEnumerable(ushort index)
        {
            Clone_FieldIndex enu = (Clone_FieldIndex)index;
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                case Clone_FieldIndex.ClonePath:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsLoqui(ushort index)
        {
            Clone_FieldIndex enu = (Clone_FieldIndex)index;
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                case Clone_FieldIndex.ClonePath:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsSingleton(ushort index)
        {
            Clone_FieldIndex enu = (Clone_FieldIndex)index;
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                case Clone_FieldIndex.ClonePath:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static string GetNthName(ushort index)
        {
            Clone_FieldIndex enu = (Clone_FieldIndex)index;
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                    return "Nickname";
                case Clone_FieldIndex.ClonePath:
                    return "ClonePath";
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsNthDerivative(ushort index)
        {
            Clone_FieldIndex enu = (Clone_FieldIndex)index;
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                case Clone_FieldIndex.ClonePath:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsProtected(ushort index)
        {
            Clone_FieldIndex enu = (Clone_FieldIndex)index;
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                case Clone_FieldIndex.ClonePath:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static Type GetNthType(ushort index)
        {
            Clone_FieldIndex enu = (Clone_FieldIndex)index;
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                    return typeof(String);
                case Clone_FieldIndex.ClonePath:
                    return typeof(String);
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        #region Interface
        ProtocolKey ILoquiRegistration.ProtocolKey => ProtocolKey;
        ObjectKey ILoquiRegistration.ObjectKey => ObjectKey;
        string ILoquiRegistration.GUID => GUID;
        int ILoquiRegistration.FieldCount => FieldCount;
        Type ILoquiRegistration.MaskType => MaskType;
        Type ILoquiRegistration.ErrorMaskType => ErrorMaskType;
        Type ILoquiRegistration.ClassType => ClassType;
        Type ILoquiRegistration.SetterType => SetterType;
        Type ILoquiRegistration.GetterType => GetterType;
        Type ILoquiRegistration.CommonType => CommonType;
        string ILoquiRegistration.FullName => FullName;
        string ILoquiRegistration.Name => Name;
        string ILoquiRegistration.Namespace => Namespace;
        byte ILoquiRegistration.GenericCount => GenericCount;
        Type ILoquiRegistration.GenericRegistrationType => GenericRegistrationType;
        ushort? ILoquiRegistration.GetNameIndex(StringCaseAgnostic name) => GetNameIndex(name);
        bool ILoquiRegistration.GetNthIsEnumerable(ushort index) => GetNthIsEnumerable(index);
        bool ILoquiRegistration.GetNthIsLoqui(ushort index) => GetNthIsLoqui(index);
        bool ILoquiRegistration.GetNthIsSingleton(ushort index) => GetNthIsSingleton(index);
        string ILoquiRegistration.GetNthName(ushort index) => GetNthName(index);
        bool ILoquiRegistration.IsNthDerivative(ushort index) => IsNthDerivative(index);
        bool ILoquiRegistration.IsProtected(ushort index) => IsProtected(index);
        Type ILoquiRegistration.GetNthType(ushort index) => GetNthType(index);
        #endregion

    }
    #endregion

    #region Extensions
    public static class CloneCommon
    {
        #region Copy Fields From
        public static void CopyFieldsFrom(
            this IClone item,
            ICloneGetter rhs,
            Clone_CopyMask copyMask = null,
            ICloneGetter def = null,
            NotifyingFireParameters? cmds = null)
        {
            CloneCommon.CopyFieldsFrom(
                item: item,
                rhs: rhs,
                def: def,
                doErrorMask: false,
                errorMask: null,
                copyMask: copyMask,
                cmds: cmds);
        }

        public static void CopyFieldsFrom(
            this IClone item,
            ICloneGetter rhs,
            out Clone_ErrorMask errorMask,
            Clone_CopyMask copyMask = null,
            ICloneGetter def = null,
            NotifyingFireParameters? cmds = null)
        {
            CloneCommon.CopyFieldsFrom(
                item: item,
                rhs: rhs,
                def: def,
                doErrorMask: true,
                errorMask: out errorMask,
                copyMask: copyMask,
                cmds: cmds);
        }

        public static void CopyFieldsFrom(
            this IClone item,
            ICloneGetter rhs,
            ICloneGetter def,
            bool doErrorMask,
            out Clone_ErrorMask errorMask,
            Clone_CopyMask copyMask,
            NotifyingFireParameters? cmds)
        {
            Clone_ErrorMask retErrorMask = null;
            Func<Clone_ErrorMask> maskGetter = () =>
            {
                if (retErrorMask == null)
                {
                    retErrorMask = new Clone_ErrorMask();
                }
                return retErrorMask;
            };
            CopyFieldsFrom(
                item: item,
                rhs: rhs,
                def: def,
                doErrorMask: true,
                errorMask: maskGetter,
                copyMask: copyMask,
                cmds: cmds);
            errorMask = retErrorMask;
        }

        public static void CopyFieldsFrom(
            this IClone item,
            ICloneGetter rhs,
            ICloneGetter def,
            bool doErrorMask,
            Func<Clone_ErrorMask> errorMask,
            Clone_CopyMask copyMask,
            NotifyingFireParameters? cmds)
        {
            if (copyMask?.Nickname ?? true)
            {
                item.Nickname = rhs.Nickname;
            }
            if (copyMask?.ClonePath ?? true)
            {
                item.ClonePath = rhs.ClonePath;
            }
        }

        #endregion

        public static void SetNthObjectHasBeenSet(
            ushort index,
            bool on,
            IClone obj,
            NotifyingFireParameters? cmds = null)
        {
            Clone_FieldIndex enu = (Clone_FieldIndex)index;
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                    break;
                case Clone_FieldIndex.ClonePath:
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static void UnsetNthObject(
            ushort index,
            IClone obj,
            NotifyingUnsetParameters? cmds = null)
        {
            Clone_FieldIndex enu = (Clone_FieldIndex)index;
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                    obj.Nickname = default(String);
                    break;
                case Clone_FieldIndex.ClonePath:
                    obj.ClonePath = default(String);
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthObjectHasBeenSet(
            ushort index,
            IClone obj)
        {
            Clone_FieldIndex enu = (Clone_FieldIndex)index;
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                case Clone_FieldIndex.ClonePath:
                    return true;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static object GetNthObject(
            ushort index,
            ICloneGetter obj)
        {
            Clone_FieldIndex enu = (Clone_FieldIndex)index;
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                    return obj.Nickname;
                case Clone_FieldIndex.ClonePath:
                    return obj.ClonePath;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static void Clear(
            IClone item,
            NotifyingUnsetParameters? cmds = null)
        {
            item.Nickname = default(String);
            item.ClonePath = default(String);
        }

        public static Clone_Mask<bool> GetEqualsMask(
            this ICloneGetter item,
            ICloneGetter rhs)
        {
            var ret = new Clone_Mask<bool>();
            FillEqualsMask(item, rhs, ret);
            return ret;
        }

        public static void FillEqualsMask(
            ICloneGetter item,
            ICloneGetter rhs,
            Clone_Mask<bool> ret)
        {
            if (rhs == null) return;
            ret.Nickname = object.Equals(item.Nickname, rhs.Nickname);
            ret.ClonePath = object.Equals(item.ClonePath, rhs.ClonePath);
        }

        public static string ToString(
            this ICloneGetter item,
            string name = null,
            Clone_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            item.ToString(fg, name, printMask);
            return fg.ToString();
        }

        public static void ToString(
            this ICloneGetter item,
            FileGeneration fg,
            string name = null,
            Clone_Mask<bool> printMask = null)
        {
            if (name == null)
            {
                fg.AppendLine($"{nameof(Clone)} =>");
            }
            else
            {
                fg.AppendLine($"{name} ({nameof(Clone)}) =>");
            }
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.Nickname ?? true)
                {
                    fg.AppendLine($"Nickname => {item.Nickname}");
                }
                if (printMask?.ClonePath ?? true)
                {
                    fg.AppendLine($"ClonePath => {item.ClonePath}");
                }
            }
            fg.AppendLine("]");
        }

        public static bool HasBeenSet(
            this ICloneGetter item,
            Clone_Mask<bool?> checkMask)
        {
            return true;
        }

        public static Clone_Mask<bool> GetHasBeenSetMask(ICloneGetter item)
        {
            var ret = new Clone_Mask<bool>();
            ret.Nickname = true;
            ret.ClonePath = true;
            return ret;
        }

        #region XML Translation
        #region XML Write
        public static void Write_XML(
            XmlWriter writer,
            ICloneGetter item,
            bool doMasks,
            out Clone_ErrorMask errorMask,
            string name = null)
        {
            Clone_ErrorMask errMaskRet = null;
            Write_XML_Internal(
                writer: writer,
                name: name,
                item: item,
                doMasks: doMasks,
                errorMask: doMasks ? () => errMaskRet ?? (errMaskRet = new Clone_ErrorMask()) : default(Func<Clone_ErrorMask>));
            errorMask = errMaskRet;
        }

        private static void Write_XML_Internal(
            XmlWriter writer,
            ICloneGetter item,
            bool doMasks,
            Func<Clone_ErrorMask> errorMask,
            string name = null)
        {
            try
            {
                using (new ElementWrapper(writer, name ?? "HarmonizeGitCloner.Clone"))
                {
                    if (name != null)
                    {
                        writer.WriteAttributeString("type", "HarmonizeGitCloner.Clone");
                    }
                    {
                        Exception subMask;
                        StringXmlTranslation.Instance.Write(
                            writer,
                            nameof(item.Nickname),
                            item.Nickname,
                            doMasks: doMasks,
                            errorMask: out subMask);
                        if (doMasks && subMask != null)
                        {
                            errorMask().Nickname = subMask;
                        }
                    }
                    {
                        Exception subMask;
                        StringXmlTranslation.Instance.Write(
                            writer,
                            nameof(item.ClonePath),
                            item.ClonePath,
                            doMasks: doMasks,
                            errorMask: out subMask);
                        if (doMasks && subMask != null)
                        {
                            errorMask().ClonePath = subMask;
                        }
                    }
                }
            }
            catch (Exception ex)
            when (doMasks)
            {
                errorMask().Overall = ex;
            }
        }
        #endregion

        #endregion

    }
    #endregion

    #region Modules

    #region Mask
    public class Clone_Mask<T> : IMask<T>, IEquatable<Clone_Mask<T>>
    {
        #region Ctors
        public Clone_Mask()
        {
        }

        public Clone_Mask(T initialValue)
        {
            this.Nickname = initialValue;
            this.ClonePath = initialValue;
        }
        #endregion

        #region Members
        public T Nickname;
        public T ClonePath;
        #endregion

        #region Equals
        public override bool Equals(object obj)
        {
            if (!(obj is Clone_Mask<T> rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(Clone_Mask<T> rhs)
        {
            if (rhs == null) return false;
            if (!object.Equals(this.Nickname, rhs.Nickname)) return false;
            if (!object.Equals(this.ClonePath, rhs.ClonePath)) return false;
            return true;
        }
        public override int GetHashCode()
        {
            int ret = 0;
            ret = ret.CombineHashCode(this.Nickname?.GetHashCode());
            ret = ret.CombineHashCode(this.ClonePath?.GetHashCode());
            return ret;
        }

        #endregion

        #region All Equal
        public bool AllEqual(Func<T, bool> eval)
        {
            if (!eval(this.Nickname)) return false;
            if (!eval(this.ClonePath)) return false;
            return true;
        }
        #endregion

        #region Translate
        public Clone_Mask<R> Translate<R>(Func<T, R> eval)
        {
            var ret = new Clone_Mask<R>();
            this.Translate_InternalFill(ret, eval);
            return ret;
        }

        protected void Translate_InternalFill<R>(Clone_Mask<R> obj, Func<T, R> eval)
        {
            obj.Nickname = eval(this.Nickname);
            obj.ClonePath = eval(this.ClonePath);
        }
        #endregion

        #region Clear Enumerables
        public void ClearEnumerables()
        {
        }
        #endregion

        #region To String
        public override string ToString()
        {
            return ToString(printMask: null);
        }

        public string ToString(Clone_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            ToString(fg, printMask);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg, Clone_Mask<bool> printMask = null)
        {
            fg.AppendLine($"{nameof(Clone_Mask<T>)} =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.Nickname ?? true)
                {
                    fg.AppendLine($"Nickname => {Nickname.ToStringSafe()}");
                }
                if (printMask?.ClonePath ?? true)
                {
                    fg.AppendLine($"ClonePath => {ClonePath.ToStringSafe()}");
                }
            }
            fg.AppendLine("]");
        }
        #endregion

    }

    public class Clone_ErrorMask : IErrorMask
    {
        #region Members
        public Exception Overall { get; set; }
        private List<string> _warnings;
        public List<string> Warnings
        {
            get
            {
                if (_warnings == null)
                {
                    _warnings = new List<string>();
                }
                return _warnings;
            }
        }
        public Exception Nickname;
        public Exception ClonePath;
        #endregion

        #region IErrorMask
        public void SetNthException(ushort index, Exception ex)
        {
            Clone_FieldIndex enu = (Clone_FieldIndex)index;
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                    this.Nickname = ex;
                    break;
                case Clone_FieldIndex.ClonePath:
                    this.ClonePath = ex;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthMask(ushort index, object obj)
        {
            Clone_FieldIndex enu = (Clone_FieldIndex)index;
            switch (enu)
            {
                case Clone_FieldIndex.Nickname:
                    this.Nickname = (Exception)obj;
                    break;
                case Clone_FieldIndex.ClonePath:
                    this.ClonePath = (Exception)obj;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }
        #endregion

        #region To String
        public override string ToString()
        {
            var fg = new FileGeneration();
            ToString(fg);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg)
        {
            fg.AppendLine("Clone_ErrorMask =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (this.Overall != null)
                {
                    fg.AppendLine("Overall =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        fg.AppendLine($"{this.Overall}");
                    }
                    fg.AppendLine("]");
                }
                ToString_FillInternal(fg);
            }
            fg.AppendLine("]");
        }
        protected void ToString_FillInternal(FileGeneration fg)
        {
            if (Nickname != null)
            {
                fg.AppendLine($"Nickname => {Nickname.ToStringSafe()}");
            }
            if (ClonePath != null)
            {
                fg.AppendLine($"ClonePath => {ClonePath.ToStringSafe()}");
            }
        }
        #endregion

        #region Combine
        public Clone_ErrorMask Combine(Clone_ErrorMask rhs)
        {
            var ret = new Clone_ErrorMask();
            ret.Nickname = this.Nickname.Combine(rhs.Nickname);
            ret.ClonePath = this.ClonePath.Combine(rhs.ClonePath);
            return ret;
        }
        public static Clone_ErrorMask Combine(Clone_ErrorMask lhs, Clone_ErrorMask rhs)
        {
            if (lhs != null && rhs != null) return lhs.Combine(rhs);
            return lhs ?? rhs;
        }
        #endregion

    }
    public class Clone_CopyMask
    {
        #region Members
        public bool Nickname;
        public bool ClonePath;
        #endregion

    }
    #endregion


    #endregion

}
