/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Loqui;
using Noggog;
using Noggog.Notifying;
using HarmonizeGitCloner.Internals;
using ReactiveUI;
using DynamicData;
using CSharpExt.Rx;
using System.Xml;
using System.Xml.Linq;
using System.IO;
using Noggog.Xml;
using Loqui.Xml;
using Loqui.Internal;
using System.Diagnostics;
using System.Collections.Specialized;

namespace HarmonizeGitCloner
{
    #region Class
    public partial class CloneSpec :
        LoquiNotifyingObject,
        ICloneSpec,
        ILoquiObjectSetter<CloneSpec>,
        IEquatable<CloneSpec>,
        IEqualsMask
    {
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => CloneSpec_Registration.Instance;
        public static CloneSpec_Registration Registration => CloneSpec_Registration.Instance;
        protected object CommonInstance => CloneSpecCommon.Instance;
        object ILoquiObject.CommonInstance => this.CommonInstance;

        #region Ctor
        public CloneSpec()
        {
            CustomCtor();
        }
        partial void CustomCtor();
        #endregion

        #region ExplicitClones
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private readonly SourceList<Clone> _ExplicitClones = new SourceList<Clone>();
        public ISourceList<Clone> ExplicitClones => _ExplicitClones;
        #region Interface Members
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IList<Clone> ICloneSpec.ExplicitClones => _ExplicitClones;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IReadOnlyList<ICloneGetter> ICloneSpecGetter.ExplicitClones => _ExplicitClones;
        #endregion

        #endregion

        IMask<bool> IEqualsMask.GetEqualsIMask(object rhs, EqualsMaskHelper.Include include) => this.GetEqualsMask((ICloneSpecGetter)rhs, include);
        #region To String

        public void ToString(
            FileGeneration fg,
            string name = null)
        {
            CloneSpecMixIn.ToString(
                item: this,
                name: name);
        }

        #endregion

        IMask<bool> ILoquiObjectGetter.GetHasBeenSetIMask() => this.GetHasBeenSetMask();
        #region Equals and Hash
        public override bool Equals(object obj)
        {
            if (!(obj is ICloneSpecGetter rhs)) return false;
            return ((CloneSpecCommon)((ILoquiObject)this).CommonInstance).Equals(this, rhs);
        }

        public bool Equals(CloneSpec obj)
        {
            return ((CloneSpecCommon)((ILoquiObject)this).CommonInstance).Equals(this, obj);
        }

        public override int GetHashCode() => ((CloneSpecCommon)((ILoquiObject)this).CommonInstance).GetHashCode(this);

        #endregion

        #region Xml Translation
        protected object XmlWriteTranslator => CloneSpecXmlWriteTranslation.Instance;
        object IXmlItem.XmlWriteTranslator => this.XmlWriteTranslator;
        #region Xml Create
        [DebuggerStepThrough]
        public static CloneSpec CreateFromXml(
            XElement node,
            MissingCreate missing = MissingCreate.New,
            CloneSpec_TranslationMask translationMask = null)
        {
            return CreateFromXml(
                missing: missing,
                node: node,
                errorMask: null,
                translationMask: translationMask?.GetCrystal());
        }

        [DebuggerStepThrough]
        public static CloneSpec CreateFromXml(
            XElement node,
            out CloneSpec_ErrorMask errorMask,
            bool doMasks = true,
            CloneSpec_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            var ret = CreateFromXml(
                missing: missing,
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask.GetCrystal());
            errorMask = CloneSpec_ErrorMask.Factory(errorMaskBuilder);
            return ret;
        }

        public static CloneSpec CreateFromXml(
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            MissingCreate missing = MissingCreate.New)
        {
            switch (missing)
            {
                case MissingCreate.New:
                case MissingCreate.Null:
                    if (node == null) return missing == MissingCreate.New ? new CloneSpec() : null;
                    break;
                default:
                    break;
            }
            var ret = new CloneSpec();
            try
            {
                foreach (var elem in node.Elements())
                {
                    CloneSpecXmlCreateTranslation.FillPublicElementXml(
                        item: ret,
                        node: elem,
                        name: elem.Name.LocalName,
                        errorMask: errorMask,
                        translationMask: translationMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
            return ret;
        }

        public static CloneSpec CreateFromXml(
            string path,
            MissingCreate missing = MissingCreate.New,
            CloneSpec_TranslationMask translationMask = null)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            return CreateFromXml(
                missing: missing,
                node: node,
                translationMask: translationMask);
        }

        public static CloneSpec CreateFromXml(
            string path,
            out CloneSpec_ErrorMask errorMask,
            CloneSpec_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            return CreateFromXml(
                missing: missing,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static CloneSpec CreateFromXml(
            string path,
            ErrorMaskBuilder errorMask,
            CloneSpec_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            return CreateFromXml(
                missing: missing,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask?.GetCrystal());
        }

        public static CloneSpec CreateFromXml(
            Stream stream,
            MissingCreate missing = MissingCreate.New,
            CloneSpec_TranslationMask translationMask = null)
        {
            var node = XDocument.Load(stream).Root;
            return CreateFromXml(
                missing: missing,
                node: node,
                translationMask: translationMask);
        }

        public static CloneSpec CreateFromXml(
            Stream stream,
            out CloneSpec_ErrorMask errorMask,
            CloneSpec_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            var node = XDocument.Load(stream).Root;
            return CreateFromXml(
                missing: missing,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static CloneSpec CreateFromXml(
            Stream stream,
            ErrorMaskBuilder errorMask,
            CloneSpec_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            var node = XDocument.Load(stream).Root;
            return CreateFromXml(
                missing: missing,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask?.GetCrystal());
        }

        #endregion

        #region Xml Copy In
        public void CopyInXml(
            XElement node,
            MissingCreate missing = MissingCreate.New)
        {
            CopyInXml_Internal(
                missing: missing,
                node: node,
                errorMask: null,
                translationMask: null);
        }

        public virtual void CopyInXml(
            XElement node,
            out CloneSpec_ErrorMask errorMask,
            CloneSpec_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New,
            bool doMasks = true)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            CopyInXml_Internal(
                missing: missing,
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = CloneSpec_ErrorMask.Factory(errorMaskBuilder);
        }

        protected void CopyInXml_Internal(
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            MissingCreate missing = MissingCreate.New)
        {
            LoquiXmlTranslation<CloneSpec>.Instance.CopyIn(
                missing: missing,
                node: node,
                item: this,
                skipProtected: true,
                errorMask: errorMask,
                translationMask: translationMask);
        }

        public void CopyInXml(
            string path,
            MissingCreate missing = MissingCreate.New)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            this.CopyInXml(
                missing: missing,
                node: node);
        }

        public void CopyInXml(
            string path,
            out CloneSpec_ErrorMask errorMask,
            CloneSpec_TranslationMask translationMask,
            MissingCreate missing = MissingCreate.New,
            bool doMasks = true)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            this.CopyInXml(
                missing: missing,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask,
                doMasks: doMasks);
        }

        public void CopyInXml(
            Stream stream,
            MissingCreate missing = MissingCreate.New)
        {
            var node = XDocument.Load(stream).Root;
            this.CopyInXml(
                missing: missing,
                node: node);
        }

        public void CopyInXml(
            Stream stream,
            out CloneSpec_ErrorMask errorMask,
            CloneSpec_TranslationMask translationMask,
            MissingCreate missing = MissingCreate.New,
            bool doMasks = true)
        {
            var node = XDocument.Load(stream).Root;
            this.CopyInXml(
                missing: missing,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask,
                doMasks: doMasks);
        }

        #endregion

        #endregion

        public CloneSpec Copy(
            CloneSpec_CopyMask copyMask = null,
            CloneSpec def = null)
        {
            return CloneSpec.Copy(
                this,
                copyMask: copyMask,
                def: def);
        }

        public static CloneSpec Copy(
            CloneSpec item,
            CloneSpec_CopyMask copyMask = null,
            CloneSpec def = null)
        {
            CloneSpec ret;
            if (item.GetType().Equals(typeof(CloneSpec)))
            {
                ret = new CloneSpec();
            }
            else
            {
                ret = (CloneSpec)System.Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public static CloneSpec Copy_ToLoqui(
            CloneSpec item,
            CloneSpec_CopyMask copyMask = null,
            CloneSpec def = null)
        {
            CloneSpec ret;
            if (item.GetType().Equals(typeof(CloneSpec)))
            {
                ret = new CloneSpec() as CloneSpec;
            }
            else
            {
                ret = (CloneSpec)System.Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public void CopyFieldsFrom(CloneSpec rhs)
        {
            this.CopyFieldsFrom(
                rhs: rhs,
                def: null,
                doMasks: false,
                errorMask: out var errMask,
                copyMask: null);
        }

        public void CopyFieldsFrom(
            CloneSpec rhs,
            CloneSpec_CopyMask copyMask,
            CloneSpec def = null)
        {
            this.CopyFieldsFrom(
                rhs: rhs,
                def: def,
                doMasks: false,
                errorMask: out var errMask,
                copyMask: copyMask);
        }

        public void CopyFieldsFrom(
            CloneSpec rhs,
            out CloneSpec_ErrorMask errorMask,
            CloneSpec_CopyMask copyMask = null,
            CloneSpec def = null,
            bool doMasks = true)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            CloneSpecCommon.CopyFieldsFrom(
                item: this,
                rhs: rhs,
                def: def,
                errorMask: errorMaskBuilder,
                copyMask: copyMask);
            errorMask = CloneSpec_ErrorMask.Factory(errorMaskBuilder);
        }

        public void CopyFieldsFrom(
            CloneSpec rhs,
            ErrorMaskBuilder errorMask,
            CloneSpec_CopyMask copyMask = null,
            CloneSpec def = null)
        {
            CloneSpecCommon.CopyFieldsFrom(
                item: this,
                rhs: rhs,
                def: def,
                errorMask: errorMask,
                copyMask: copyMask);
        }

        protected void SetNthObject(ushort index, object obj)
        {
            CloneSpec_FieldIndex enu = (CloneSpec_FieldIndex)index;
            switch (enu)
            {
                case CloneSpec_FieldIndex.ExplicitClones:
                    this._ExplicitClones.SetTo((IList<Clone>)obj);
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void Clear()
        {
            CloneSpecCommon.Instance.Clear(this);
        }

        public static CloneSpec Create(IEnumerable<KeyValuePair<ushort, object>> fields)
        {
            var ret = new CloneSpec();
            foreach (var pair in fields)
            {
                CopyInInternal_CloneSpec(ret, pair);
            }
            return ret;
        }

        protected static void CopyInInternal_CloneSpec(CloneSpec obj, KeyValuePair<ushort, object> pair)
        {
            if (!EnumExt.TryParse(pair.Key, out CloneSpec_FieldIndex enu))
            {
                throw new ArgumentException($"Unknown index: {pair.Key}");
            }
            switch (enu)
            {
                case CloneSpec_FieldIndex.ExplicitClones:
                    obj._ExplicitClones.SetTo((IList<Clone>)pair.Value);
                    break;
                default:
                    throw new ArgumentException($"Unknown enum type: {enu}");
            }
        }
    }
    #endregion

    #region Interface
    public partial interface ICloneSpec :
        ICloneSpecGetter,
        ILoquiObjectSetter<ICloneSpec>
    {
        new IList<Clone> ExplicitClones { get; }
        void CopyFieldsFrom(
            CloneSpec rhs,
            ErrorMaskBuilder errorMask = null,
            CloneSpec_CopyMask copyMask = null,
            CloneSpec def = null);
    }

    public partial interface ICloneSpecGetter :
        ILoquiObject,
        ILoquiObject<ICloneSpecGetter>,
        IXmlItem
    {
        #region ExplicitClones
        IReadOnlyList<ICloneGetter> ExplicitClones { get; }
        #endregion

    }

    #endregion

    #region Common MixIn
    public static class CloneSpecMixIn
    {
        public static void Clear(this ICloneSpec item)
        {
            ((CloneSpecCommon)((ILoquiObject)item).CommonInstance).Clear(item: item);
        }

        public static CloneSpec_Mask<bool> GetEqualsMask(
            this ICloneSpecGetter item,
            ICloneSpecGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            return ((CloneSpecCommon)((ILoquiObject)item).CommonInstance).GetEqualsMask(
                item: item,
                rhs: rhs,
                include: include);
        }

        public static string ToString(
            this ICloneSpecGetter item,
            string name = null,
            CloneSpec_Mask<bool> printMask = null)
        {
            return ((CloneSpecCommon)((ILoquiObject)item).CommonInstance).ToString(
                item: item,
                name: name,
                printMask: printMask);
        }

        public static void ToString(
            this ICloneSpecGetter item,
            FileGeneration fg,
            string name = null,
            CloneSpec_Mask<bool> printMask = null)
        {
            ((CloneSpecCommon)((ILoquiObject)item).CommonInstance).ToString(
                item: item,
                fg: fg,
                name: name,
                printMask: printMask);
        }

        public static bool HasBeenSet(
            this ICloneSpecGetter item,
            CloneSpec_Mask<bool?> checkMask)
        {
            return ((CloneSpecCommon)((ILoquiObject)item).CommonInstance).HasBeenSet(
                item: item,
                checkMask: checkMask);
        }

        public static CloneSpec_Mask<bool> GetHasBeenSetMask(this ICloneSpecGetter item)
        {
            var ret = new CloneSpec_Mask<bool>();
            ((CloneSpecCommon)((ILoquiObject)item).CommonInstance).FillHasBeenSetMask(
                item: item,
                mask: ret);
            return ret;
        }

        public static bool Equals(
            this ICloneSpecGetter item,
            ICloneSpecGetter rhs)
        {
            return ((CloneSpecCommon)((ILoquiObject)item).CommonInstance).Equals(
                lhs: item,
                rhs: rhs);
        }

    }
    #endregion

}

namespace HarmonizeGitCloner.Internals
{
    #region Field Index
    public enum CloneSpec_FieldIndex
    {
        ExplicitClones = 0,
    }
    #endregion

    #region Registration
    public class CloneSpec_Registration : ILoquiRegistration
    {
        public static readonly CloneSpec_Registration Instance = new CloneSpec_Registration();

        public static ProtocolKey ProtocolKey => ProtocolDefinition_HarmonizeGitCloner.ProtocolKey;

        public static readonly ObjectKey ObjectKey = new ObjectKey(
            protocolKey: ProtocolDefinition_HarmonizeGitCloner.ProtocolKey,
            msgID: 1,
            version: 0);

        public const string GUID = "651b1c2a-304e-4f21-85cb-d1088f16dc21";

        public const ushort AdditionalFieldCount = 1;

        public const ushort FieldCount = 1;

        public static readonly Type MaskType = typeof(CloneSpec_Mask<>);

        public static readonly Type ErrorMaskType = typeof(CloneSpec_ErrorMask);

        public static readonly Type ClassType = typeof(CloneSpec);

        public static readonly Type GetterType = typeof(ICloneSpecGetter);

        public static readonly Type InternalGetterType = null;

        public static readonly Type SetterType = typeof(ICloneSpec);

        public static readonly Type InternalSetterType = null;

        public static readonly Type CommonType = typeof(CloneSpecCommon);

        public const string FullName = "HarmonizeGitCloner.CloneSpec";

        public const string Name = "CloneSpec";

        public const string Namespace = "HarmonizeGitCloner";

        public const byte GenericCount = 0;

        public static readonly Type GenericRegistrationType = null;

        public static ushort? GetNameIndex(StringCaseAgnostic str)
        {
            switch (str.Upper)
            {
                case "EXPLICITCLONES":
                    return (ushort)CloneSpec_FieldIndex.ExplicitClones;
                default:
                    return null;
            }
        }

        public static bool GetNthIsEnumerable(ushort index)
        {
            CloneSpec_FieldIndex enu = (CloneSpec_FieldIndex)index;
            switch (enu)
            {
                case CloneSpec_FieldIndex.ExplicitClones:
                    return true;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsLoqui(ushort index)
        {
            CloneSpec_FieldIndex enu = (CloneSpec_FieldIndex)index;
            switch (enu)
            {
                case CloneSpec_FieldIndex.ExplicitClones:
                    return true;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsSingleton(ushort index)
        {
            CloneSpec_FieldIndex enu = (CloneSpec_FieldIndex)index;
            switch (enu)
            {
                case CloneSpec_FieldIndex.ExplicitClones:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static string GetNthName(ushort index)
        {
            CloneSpec_FieldIndex enu = (CloneSpec_FieldIndex)index;
            switch (enu)
            {
                case CloneSpec_FieldIndex.ExplicitClones:
                    return "ExplicitClones";
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsNthDerivative(ushort index)
        {
            CloneSpec_FieldIndex enu = (CloneSpec_FieldIndex)index;
            switch (enu)
            {
                case CloneSpec_FieldIndex.ExplicitClones:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsProtected(ushort index)
        {
            CloneSpec_FieldIndex enu = (CloneSpec_FieldIndex)index;
            switch (enu)
            {
                case CloneSpec_FieldIndex.ExplicitClones:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static Type GetNthType(ushort index)
        {
            CloneSpec_FieldIndex enu = (CloneSpec_FieldIndex)index;
            switch (enu)
            {
                case CloneSpec_FieldIndex.ExplicitClones:
                    return typeof(IList<Clone>);
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static readonly Type XmlWriteTranslation = typeof(CloneSpecXmlWriteTranslation);
        #region Interface
        ProtocolKey ILoquiRegistration.ProtocolKey => ProtocolKey;
        ObjectKey ILoquiRegistration.ObjectKey => ObjectKey;
        string ILoquiRegistration.GUID => GUID;
        ushort ILoquiRegistration.FieldCount => FieldCount;
        ushort ILoquiRegistration.AdditionalFieldCount => AdditionalFieldCount;
        Type ILoquiRegistration.MaskType => MaskType;
        Type ILoquiRegistration.ErrorMaskType => ErrorMaskType;
        Type ILoquiRegistration.ClassType => ClassType;
        Type ILoquiRegistration.SetterType => SetterType;
        Type ILoquiRegistration.InternalSetterType => InternalSetterType;
        Type ILoquiRegistration.GetterType => GetterType;
        Type ILoquiRegistration.InternalGetterType => InternalGetterType;
        Type ILoquiRegistration.CommonType => CommonType;
        string ILoquiRegistration.FullName => FullName;
        string ILoquiRegistration.Name => Name;
        string ILoquiRegistration.Namespace => Namespace;
        byte ILoquiRegistration.GenericCount => GenericCount;
        Type ILoquiRegistration.GenericRegistrationType => GenericRegistrationType;
        ushort? ILoquiRegistration.GetNameIndex(StringCaseAgnostic name) => GetNameIndex(name);
        bool ILoquiRegistration.GetNthIsEnumerable(ushort index) => GetNthIsEnumerable(index);
        bool ILoquiRegistration.GetNthIsLoqui(ushort index) => GetNthIsLoqui(index);
        bool ILoquiRegistration.GetNthIsSingleton(ushort index) => GetNthIsSingleton(index);
        string ILoquiRegistration.GetNthName(ushort index) => GetNthName(index);
        bool ILoquiRegistration.IsNthDerivative(ushort index) => IsNthDerivative(index);
        bool ILoquiRegistration.IsProtected(ushort index) => IsProtected(index);
        Type ILoquiRegistration.GetNthType(ushort index) => GetNthType(index);
        #endregion

    }
    #endregion

    #region Common
    public partial class CloneSpecCommon
    {
        public static readonly CloneSpecCommon Instance = new CloneSpecCommon();

        #region Copy Fields From
        public static void CopyFieldsFrom(
            CloneSpec item,
            CloneSpec rhs,
            CloneSpec def,
            ErrorMaskBuilder errorMask,
            CloneSpec_CopyMask copyMask)
        {
            if (copyMask?.ExplicitClones.Overall != CopyOption.Skip)
            {
                errorMask?.PushIndex((int)CloneSpec_FieldIndex.ExplicitClones);
                try
                {
                    item.ExplicitClones.SetToWithDefault<Clone, Clone>(
                        rhs: rhs.ExplicitClones,
                        def: def?.ExplicitClones,
                        converter: (r, d) =>
                        {
                            switch (copyMask?.ExplicitClones.Overall ?? CopyOption.Reference)
                            {
                                case CopyOption.Reference:
                                    return (Clone)r;
                                case CopyOption.MakeCopy:
                                    return Clone.Copy(
                                        r,
                                        copyMask?.ExplicitClones?.Specific,
                                        def: d);
                                default:
                                    throw new NotImplementedException($"Unknown CopyOption {copyMask?.ExplicitClones.Overall}. Cannot execute copy.");
                            }
                        });
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
        }

        #endregion

        partial void ClearPartial();

        public virtual void Clear(ICloneSpec item)
        {
            ClearPartial();
            item.ExplicitClones.Clear();
        }

        public CloneSpec_Mask<bool> GetEqualsMask(
            ICloneSpecGetter item,
            ICloneSpecGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            var ret = new CloneSpec_Mask<bool>();
            ((CloneSpecCommon)((ILoquiObject)item).CommonInstance).FillEqualsMask(
                item: item,
                rhs: rhs,
                ret: ret,
                include: include);
            return ret;
        }

        public void FillEqualsMask(
            ICloneSpecGetter item,
            ICloneSpecGetter rhs,
            CloneSpec_Mask<bool> ret,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            if (rhs == null) return;
            ret.ExplicitClones = item.ExplicitClones.CollectionEqualsHelper(
                rhs.ExplicitClones,
                (loqLhs, loqRhs) => loqLhs.GetEqualsMask(loqRhs, include),
                include);
        }

        public string ToString(
            ICloneSpecGetter item,
            string name = null,
            CloneSpec_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            ToString(
                item: item,
                fg: fg,
                name: name,
                printMask: printMask);
            return fg.ToString();
        }

        public void ToString(
            ICloneSpecGetter item,
            FileGeneration fg,
            string name = null,
            CloneSpec_Mask<bool> printMask = null)
        {
            if (name == null)
            {
                fg.AppendLine($"CloneSpec =>");
            }
            else
            {
                fg.AppendLine($"{name} (CloneSpec) =>");
            }
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                ToStringFields(
                    item: item,
                    fg: fg,
                    printMask: printMask);
            }
            fg.AppendLine("]");
        }

        protected static void ToStringFields(
            ICloneSpecGetter item,
            FileGeneration fg,
            CloneSpec_Mask<bool> printMask = null)
        {
            if (printMask?.ExplicitClones?.Overall ?? true)
            {
                fg.AppendLine("ExplicitClones =>");
                fg.AppendLine("[");
                using (new DepthWrapper(fg))
                {
                    foreach (var subItem in item.ExplicitClones)
                    {
                        fg.AppendLine("[");
                        using (new DepthWrapper(fg))
                        {
                            subItem?.ToString(fg, "Item");
                        }
                        fg.AppendLine("]");
                    }
                }
                fg.AppendLine("]");
            }
        }

        public bool HasBeenSet(
            ICloneSpecGetter item,
            CloneSpec_Mask<bool?> checkMask)
        {
            return true;
        }

        public void FillHasBeenSetMask(
            ICloneSpecGetter item,
            CloneSpec_Mask<bool> mask)
        {
            mask.ExplicitClones = new MaskItem<bool, IEnumerable<MaskItemIndexed<bool, Clone_Mask<bool>>>>(true, item.ExplicitClones.WithIndex().Select((i) => new MaskItemIndexed<bool, Clone_Mask<bool>>(i.Index, true, i.Item.GetHasBeenSetMask())));
        }

        #region Equals and Hash
        public virtual bool Equals(
            ICloneSpecGetter lhs,
            ICloneSpecGetter rhs)
        {
            if (lhs == null && rhs == null) return false;
            if (lhs == null || rhs == null) return false;
            if (!lhs.ExplicitClones.SequenceEqual(rhs.ExplicitClones)) return false;
            return true;
        }

        public virtual int GetHashCode(ICloneSpecGetter item)
        {
            int ret = 0;
            ret = HashHelper.GetHashCode(item.ExplicitClones).CombineHashCode(ret);
            return ret;
        }

        #endregion


    }
    #endregion

    #region Modules
    #region Xml Translation
    public partial class CloneSpecXmlWriteTranslation : IXmlWriteTranslator
    {
        public readonly static CloneSpecXmlWriteTranslation Instance = new CloneSpecXmlWriteTranslation();

        public static void WriteToNodeXml(
            ICloneSpecGetter item,
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            if ((translationMask?.GetShouldTranslate((int)CloneSpec_FieldIndex.ExplicitClones) ?? true))
            {
                ListXmlTranslation<ICloneGetter>.Instance.Write(
                    node: node,
                    name: nameof(item.ExplicitClones),
                    item: item.ExplicitClones,
                    fieldIndex: (int)CloneSpec_FieldIndex.ExplicitClones,
                    errorMask: errorMask,
                    translationMask: translationMask?.GetSubCrystal((int)CloneSpec_FieldIndex.ExplicitClones),
                    transl: (XElement subNode, ICloneGetter subItem, ErrorMaskBuilder listSubMask, TranslationCrystal listTranslMask) =>
                    {
                        var loquiItem = subItem;
                        ((CloneXmlWriteTranslation)((IXmlItem)loquiItem).XmlWriteTranslator).Write(
                            item: loquiItem,
                            node: subNode,
                            name: null,
                            errorMask: listSubMask,
                            translationMask: listTranslMask);
                    });
            }
        }

        public void Write(
            XElement node,
            ICloneSpecGetter item,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            var elem = new XElement(name ?? "HarmonizeGitCloner.CloneSpec");
            node.Add(elem);
            if (name != null)
            {
                elem.SetAttributeValue("type", "HarmonizeGitCloner.CloneSpec");
            }
            WriteToNodeXml(
                item: item,
                node: elem,
                errorMask: errorMask,
                translationMask: translationMask);
        }

        public void Write(
            XElement node,
            object item,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            Write(
                item: (ICloneSpecGetter)item,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
        }

        public void Write(
            XElement node,
            ICloneSpecGetter item,
            ErrorMaskBuilder errorMask,
            int fieldIndex,
            TranslationCrystal translationMask,
            string name = null)
        {
            try
            {
                errorMask?.PushIndex(fieldIndex);
                Write(
                    item: (ICloneSpecGetter)item,
                    name: name,
                    node: node,
                    errorMask: errorMask,
                    translationMask: translationMask);
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
            finally
            {
                errorMask?.PopIndex();
            }
        }

    }

    public partial class CloneSpecXmlCreateTranslation
    {
        public readonly static CloneSpecXmlCreateTranslation Instance = new CloneSpecXmlCreateTranslation();

        public static void FillPublicXml(
            ICloneSpec item,
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            try
            {
                foreach (var elem in node.Elements())
                {
                    CloneSpecXmlCreateTranslation.FillPublicElementXml(
                        item: item,
                        node: elem,
                        name: elem.Name.LocalName,
                        errorMask: errorMask,
                        translationMask: translationMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
        }

        public static void FillPublicElementXml(
            ICloneSpec item,
            XElement node,
            string name,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            switch (name)
            {
                case "ExplicitClones":
                    if ((translationMask?.GetShouldTranslate((int)CloneSpec_FieldIndex.ExplicitClones) ?? true))
                    {
                        try
                        {
                            errorMask?.PushIndex((int)CloneSpec_FieldIndex.ExplicitClones);
                            if (ListXmlTranslation<Clone>.Instance.Parse(
                                node: node,
                                enumer: out var ExplicitClonesItem,
                                transl: LoquiXmlTranslation<Clone>.Instance.Parse,
                                errorMask: errorMask,
                                translationMask: translationMask))
                            {
                                item.ExplicitClones.SetTo(ExplicitClonesItem);
                            }
                            else
                            {
                                item.ExplicitClones.Clear();
                            }
                        }
                        catch (Exception ex)
                        when (errorMask != null)
                        {
                            errorMask.ReportException(ex);
                        }
                        finally
                        {
                            errorMask?.PopIndex();
                        }
                    }
                    break;
                default:
                    break;
            }
        }

    }

    #region Xml Write Mixins
    public static class CloneSpecXmlTranslationMixIn
    {
        public static void WriteToXml(
            this ICloneSpecGetter item,
            XElement node,
            out CloneSpec_ErrorMask errorMask,
            bool doMasks = true,
            CloneSpec_TranslationMask translationMask = null,
            string name = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            ((CloneSpecXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = CloneSpec_ErrorMask.Factory(errorMaskBuilder);
        }

        public static void WriteToXml(
            this ICloneSpecGetter item,
            string path,
            out CloneSpec_ErrorMask errorMask,
            CloneSpec_TranslationMask translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            var node = new XElement("topnode");
            WriteToXml(
                item: item,
                name: name,
                node: node,
                errorMask: out errorMask,
                doMasks: doMasks,
                translationMask: translationMask);
            node.Elements().First().SaveIfChanged(path);
        }

        public static void WriteToXml(
            this ICloneSpecGetter item,
            string path,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            var node = new XElement("topnode");
            WriteToXml(
                item: item,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
            node.Elements().First().SaveIfChanged(path);
        }

        public static void WriteToXml(
            this ICloneSpecGetter item,
            Stream stream,
            out CloneSpec_ErrorMask errorMask,
            CloneSpec_TranslationMask translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            var node = new XElement("topnode");
            WriteToXml(
                item: item,
                name: name,
                node: node,
                errorMask: out errorMask,
                doMasks: doMasks,
                translationMask: translationMask);
            node.Elements().First().Save(stream);
        }

        public static void WriteToXml(
            this ICloneSpecGetter item,
            Stream stream,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            var node = new XElement("topnode");
            WriteToXml(
                item: item,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
            node.Elements().First().Save(stream);
        }

        public static void WriteToXml(
            this ICloneSpecGetter item,
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask = null,
            string name = null)
        {
            ((CloneSpecXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
        }

        public static void WriteToXml(
            this ICloneSpecGetter item,
            XElement node,
            string name = null,
            CloneSpec_TranslationMask translationMask = null)
        {
            ((CloneSpecXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: null,
                translationMask: translationMask.GetCrystal());
        }

        public static void WriteToXml(
            this ICloneSpecGetter item,
            string path,
            string name = null)
        {
            var node = new XElement("topnode");
            ((CloneSpecXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: null,
                translationMask: null);
            node.Elements().First().SaveIfChanged(path);
        }

        public static void WriteToXml(
            this ICloneSpecGetter item,
            Stream stream,
            string name = null)
        {
            var node = new XElement("topnode");
            ((CloneSpecXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: null,
                translationMask: null);
            node.Elements().First().Save(stream);
        }

    }
    #endregion

    #endregion

    #region Mask
    public class CloneSpec_Mask<T> : IMask<T>, IEquatable<CloneSpec_Mask<T>>
    {
        #region Ctors
        public CloneSpec_Mask()
        {
        }

        public CloneSpec_Mask(T initialValue)
        {
            this.ExplicitClones = new MaskItem<T, IEnumerable<MaskItemIndexed<T, Clone_Mask<T>>>>(initialValue, null);
        }
        #endregion

        #region Members
        public MaskItem<T, IEnumerable<MaskItemIndexed<T, Clone_Mask<T>>>> ExplicitClones;
        #endregion

        #region Equals
        public override bool Equals(object obj)
        {
            if (!(obj is CloneSpec_Mask<T> rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(CloneSpec_Mask<T> rhs)
        {
            if (rhs == null) return false;
            if (!object.Equals(this.ExplicitClones, rhs.ExplicitClones)) return false;
            return true;
        }
        public override int GetHashCode()
        {
            int ret = 0;
            ret = ret.CombineHashCode(this.ExplicitClones?.GetHashCode());
            return ret;
        }

        #endregion

        #region All Equal
        public bool AllEqual(Func<T, bool> eval)
        {
            if (this.ExplicitClones != null)
            {
                if (!eval(this.ExplicitClones.Overall)) return false;
                if (this.ExplicitClones.Specific != null)
                {
                    foreach (var item in this.ExplicitClones.Specific)
                    {
                        if (!eval(item.Overall)) return false;
                        if (item.Specific != null && !item.Specific.AllEqual(eval)) return false;
                    }
                }
            }
            return true;
        }
        #endregion

        #region Translate
        public CloneSpec_Mask<R> Translate<R>(Func<T, R> eval)
        {
            var ret = new CloneSpec_Mask<R>();
            this.Translate_InternalFill(ret, eval);
            return ret;
        }

        protected void Translate_InternalFill<R>(CloneSpec_Mask<R> obj, Func<T, R> eval)
        {
            if (ExplicitClones != null)
            {
                obj.ExplicitClones = new MaskItem<R, IEnumerable<MaskItemIndexed<R, Clone_Mask<R>>>>();
                obj.ExplicitClones.Overall = eval(this.ExplicitClones.Overall);
                if (ExplicitClones.Specific != null)
                {
                    List<MaskItemIndexed<R, Clone_Mask<R>>> l = new List<MaskItemIndexed<R, Clone_Mask<R>>>();
                    obj.ExplicitClones.Specific = l;
                    foreach (var item in ExplicitClones.Specific.WithIndex())
                    {
                        MaskItemIndexed<R, Clone_Mask<R>> mask = default;
                        mask.Index = item.Index;
                        if (item.Item != null)
                        {
                            mask = new MaskItemIndexed<R, Clone_Mask<R>>(item.Item.Index);
                            mask.Overall = eval(item.Item.Overall);
                            if (item.Item.Specific != null)
                            {
                                mask.Specific = item.Item.Specific.Translate(eval);
                            }
                        }
                        l.Add(mask);
                    }
                }
            }
        }
        #endregion

        #region Clear Enumerables
        public void ClearEnumerables()
        {
            this.ExplicitClones.Specific = null;
        }
        #endregion

        #region To String
        public override string ToString()
        {
            return ToString(printMask: null);
        }

        public string ToString(CloneSpec_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            ToString(fg, printMask);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg, CloneSpec_Mask<bool> printMask = null)
        {
            fg.AppendLine($"{nameof(CloneSpec_Mask<T>)} =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.ExplicitClones?.Overall ?? true)
                {
                    fg.AppendLine("ExplicitClones =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        if (ExplicitClones.Overall != null)
                        {
                            fg.AppendLine(ExplicitClones.Overall.ToString());
                        }
                        if (ExplicitClones.Specific != null)
                        {
                            foreach (var subItem in ExplicitClones.Specific)
                            {
                                fg.AppendLine("[");
                                using (new DepthWrapper(fg))
                                {
                                    subItem?.ToString(fg);
                                }
                                fg.AppendLine("]");
                            }
                        }
                    }
                    fg.AppendLine("]");
                }
            }
            fg.AppendLine("]");
        }
        #endregion

    }

    public class CloneSpec_ErrorMask : IErrorMask, IErrorMask<CloneSpec_ErrorMask>
    {
        #region Members
        public Exception Overall { get; set; }
        private List<string> _warnings;
        public List<string> Warnings
        {
            get
            {
                if (_warnings == null)
                {
                    _warnings = new List<string>();
                }
                return _warnings;
            }
        }
        public MaskItem<Exception, IEnumerable<MaskItem<Exception, Clone_ErrorMask>>> ExplicitClones;
        #endregion

        #region IErrorMask
        public object GetNthMask(int index)
        {
            CloneSpec_FieldIndex enu = (CloneSpec_FieldIndex)index;
            switch (enu)
            {
                case CloneSpec_FieldIndex.ExplicitClones:
                    return ExplicitClones;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthException(int index, Exception ex)
        {
            CloneSpec_FieldIndex enu = (CloneSpec_FieldIndex)index;
            switch (enu)
            {
                case CloneSpec_FieldIndex.ExplicitClones:
                    this.ExplicitClones = new MaskItem<Exception, IEnumerable<MaskItem<Exception, Clone_ErrorMask>>>(ex, null);
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthMask(int index, object obj)
        {
            CloneSpec_FieldIndex enu = (CloneSpec_FieldIndex)index;
            switch (enu)
            {
                case CloneSpec_FieldIndex.ExplicitClones:
                    this.ExplicitClones = (MaskItem<Exception, IEnumerable<MaskItem<Exception, Clone_ErrorMask>>>)obj;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public bool IsInError()
        {
            if (Overall != null) return true;
            if (ExplicitClones != null) return true;
            return false;
        }
        #endregion

        #region To String
        public override string ToString()
        {
            var fg = new FileGeneration();
            ToString(fg);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg)
        {
            fg.AppendLine("CloneSpec_ErrorMask =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (this.Overall != null)
                {
                    fg.AppendLine("Overall =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        fg.AppendLine($"{this.Overall}");
                    }
                    fg.AppendLine("]");
                }
                ToString_FillInternal(fg);
            }
            fg.AppendLine("]");
        }
        protected void ToString_FillInternal(FileGeneration fg)
        {
            fg.AppendLine("ExplicitClones =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (ExplicitClones.Overall != null)
                {
                    fg.AppendLine(ExplicitClones.Overall.ToString());
                }
                if (ExplicitClones.Specific != null)
                {
                    foreach (var subItem in ExplicitClones.Specific)
                    {
                        fg.AppendLine("[");
                        using (new DepthWrapper(fg))
                        {
                            subItem?.ToString(fg);
                        }
                        fg.AppendLine("]");
                    }
                }
            }
            fg.AppendLine("]");
        }
        #endregion

        #region Combine
        public CloneSpec_ErrorMask Combine(CloneSpec_ErrorMask rhs)
        {
            var ret = new CloneSpec_ErrorMask();
            ret.ExplicitClones = new MaskItem<Exception, IEnumerable<MaskItem<Exception, Clone_ErrorMask>>>(this.ExplicitClones.Overall.Combine(rhs.ExplicitClones.Overall), new List<MaskItem<Exception, Clone_ErrorMask>>(this.ExplicitClones.Specific.And(rhs.ExplicitClones.Specific)));
            return ret;
        }
        public static CloneSpec_ErrorMask Combine(CloneSpec_ErrorMask lhs, CloneSpec_ErrorMask rhs)
        {
            if (lhs != null && rhs != null) return lhs.Combine(rhs);
            return lhs ?? rhs;
        }
        #endregion

        #region Factory
        public static CloneSpec_ErrorMask Factory(ErrorMaskBuilder errorMask)
        {
            if (errorMask?.Empty ?? true) return null;
            return new CloneSpec_ErrorMask();
        }
        #endregion

    }
    public class CloneSpec_CopyMask
    {
        public CloneSpec_CopyMask()
        {
        }

        public CloneSpec_CopyMask(bool defaultOn, CopyOption deepCopyOption = CopyOption.Reference)
        {
            this.ExplicitClones = new MaskItem<CopyOption, Clone_CopyMask>(deepCopyOption, default);
        }

        #region Members
        public MaskItem<CopyOption, Clone_CopyMask> ExplicitClones;
        #endregion

    }

    public class CloneSpec_TranslationMask : ITranslationMask
    {
        #region Members
        private TranslationCrystal _crystal;
        public MaskItem<bool, Clone_TranslationMask> ExplicitClones;
        #endregion

        #region Ctors
        public CloneSpec_TranslationMask()
        {
        }

        public CloneSpec_TranslationMask(bool defaultOn)
        {
            this.ExplicitClones = new MaskItem<bool, Clone_TranslationMask>(defaultOn, null);
        }

        #endregion

        public TranslationCrystal GetCrystal()
        {
            if (_crystal != null) return _crystal;
            List<(bool On, TranslationCrystal SubCrystal)> ret = new List<(bool On, TranslationCrystal SubCrystal)>();
            GetCrystal(ret);
            _crystal = new TranslationCrystal()
            {
                Crystal = ret.ToArray()
            };
            return _crystal;
        }

        protected void GetCrystal(List<(bool On, TranslationCrystal SubCrystal)> ret)
        {
            ret.Add((ExplicitClones?.Overall ?? true, ExplicitClones?.Specific?.GetCrystal()));
        }
    }
    #endregion

    #endregion

}
